/* ============================================================================
   i18n-ui.js — the UI labels that were never given a dictionary key
   ============================================================================
   nova.js has two translation mechanisms and they cover different things. The
   `T` dictionary covers the furniture nova.js builds itself — the rail, the
   top bar, the pricing cards — and is complete: 725 keys in all 20 languages.
   The `P` phrase layer swaps whole text nodes by their exact English wording,
   for UI that React or a page's own HTML renders and that `T` can therefore
   never reach. `P` held 27 phrases.

   Measured across 34 pages in all 19 non-English languages, about half of every
   page was still English, and the count was the same in each language to within
   three points. That is the signature of strings missing from the SITE rather
   than from a language: there is nothing to look up, so every language falls
   back to English together. Filling a language column would have fixed nothing.

   So this file is the phrase layer made big enough to matter, and kept apart
   from nova.js so it can keep growing without pushing that file past the point
   anybody can read it. nova.js loads it and merges it in; a phrase here behaves
   exactly as one declared in `P`.

   HOW TO ADD TO IT

   Key by the EXACT English string as it appears on screen, including case and
   any punctuation or symbol in the same text node, then nineteen values in the
   order of L below. The match is exact and whole-node: "Upload" will not touch
   "Upload a file", which is deliberate — a substring match would rewrite words
   inside sentences and break them.

   WHAT IS DELIBERATELY NOT HERE

   Brand names (NovaClip, NovaFlap, TypeMaster, YouTube), the long prose on
   privacy.html and terms.html — those are legal text and want a translator,
   not a dictionary — and anything a page generates with a number baked into
   it, which needs a {n} template in `T` instead.
   ========================================================================= */
(function () {
  var L = ['zh','hi','es','ar','fr','bn','pt','ru','ur','id','de','ja','tr','ko','fa','uk','it','pl','vi'];

  var R = {

  /* ---- the editor: left rail, media panel, inspector, timeline ---------- */
  "Media Library": ["媒体库","मीडिया लाइब्रेरी","Biblioteca de medios","مكتبة الوسائط","Bibliothèque média","মিডিয়া লাইব্রেরি","Biblioteca de mídia","Медиатека","میڈیا لائبریری","Pustaka media","Medienbibliothek","メディアライブラリ","Medya kitaplığı","미디어 보관함","کتابخانهٔ رسانه","Медіатека","Libreria media","Biblioteka mediów","Thư viện media"],
  "Upload": ["上传","अपलोड","Subir","رفع","Importer","আপলোড","Carregar","Загрузить","اپ لوڈ","Unggah","Hochladen","アップロード","Yükle","업로드","بارگذاری","Завантажити","Carica","Prześlij","Tải lên"],
  "Drop media here": ["把媒体拖到这里","मीडिया यहाँ छोड़ें","Suelta los medios aquí","أفلت الوسائط هنا","Dépose tes fichiers ici","মিডিয়া এখানে ছাড়ো","Larga os ficheiros aqui","Перетащи файлы сюда","میڈیا یہاں چھوڑیں","Letakkan media di sini","Medien hierher ziehen","ここにメディアをドロップ","Medyayı buraya bırak","여기에 미디어를 놓으세요","رسانه را اینجا رها کن","Перетягни файли сюди","Trascina qui i file","Upuść media tutaj","Thả media vào đây"],
  "Transform": ["变换","ट्रांसफ़ॉर्म","Transformar","تحويل","Transformer","ট্রান্সফর্ম","Transformar","Трансформация","ٹرانسفارم","Transformasi","Transformieren","変形","Dönüştür","변형","دگرگونی","Трансформація","Trasforma","Przekształć","Biến đổi"],
  "Color": ["颜色","रंग","Color","اللون","Couleur","রঙ","Cor","Цвет","رنگ","Warna","Farbe","カラー","Renk","색상","رنگ","Колір","Colore","Kolor","Màu"],
  "Keyframes": ["关键帧","कीफ़्रेम","Fotogramas clave","الإطارات المفتاحية","Images clés","কীফ্রেম","Fotogramas-chave","Ключевые кадры","کی فریمز","Keyframe","Keyframes","キーフレーム","Anahtar kareler","키프레임","کلیدفریم‌ها","Ключові кадри","Fotogrammi chiave","Klatki kluczowe","Khung hình khóa"],
  "No clip selected": ["未选择片段","कोई क्लिप चुनी नहीं","Ningún clip seleccionado","لم يتم اختيار مقطع","Aucun clip sélectionné","কোনো ক্লিপ বাছাই করা হয়নি","Nenhum clipe selecionado","Клип не выбран","کوئی کلپ منتخب نہیں","Tidak ada klip dipilih","Kein Clip ausgewählt","クリップが選択されていません","Seçili klip yok","선택된 클립 없음","هیچ کلیپی انتخاب نشده","Кліп не вибрано","Nessuna clip selezionata","Nie wybrano klipu","Chưa chọn clip nào"],
  "+ Timeline": ["+ 时间线","+ टाइमलाइन","+ Línea de tiempo","+ خط زمني","+ Montage","+ টাইমলাইন","+ Linha temporal","+ Таймлайн","+ ٹائم لائن","+ Lini masa","+ Zeitleiste","+ タイムライン","+ Zaman çizelgesi","+ 타임라인","+ خط زمانی","+ Таймлайн","+ Timeline","+ Oś czasu","+ Dòng thời gian"],
  "Snap": ["吸附","स्नैप","Ajustar","محاذاة","Magnétisme","স্ন্যাপ","Ajustar","Привязка","اسنیپ","Rekat","Einrasten","スナップ","Yapış","스냅","چسبیدن","Прив'язка","Aggancia","Przyciąganie","Hít dính"],
  "tracks": ["轨道","ट्रैक","pistas","مسارات","pistes","ট্র্যাক","faixas","дорожек","ٹریکس","trek","Spuren","トラック","iz","트랙","ترک","доріжок","tracce","ścieżki","rãnh"],
  "clips": ["片段","क्लिप","clips","مقاطع","clips","ক্লিপ","clipes","клипов","کلپس","klip","Clips","クリップ","klip","클립","کلیپ","кліпів","clip","klipy","clip"],
  "Photos": ["照片","फ़ोटो","Fotos","صور","Photos","ছবি","Fotos","Фото","تصاویر","Foto","Fotos","写真","Fotoğraflar","사진","عکس","Фото","Foto","Zdjęcia","Ảnh"],
  "Footage": ["素材","फुटेज","Metraje","لقطات","Rushes","ফুটেজ","Imagens","Видеоматериал","فوٹیج","Cuplikan","Filmmaterial","映像素材","Görüntüler","영상 소스","فیلم خام","Відеоматеріал","Filmati","Materiał","Cảnh quay"],
  "Emojis": ["表情符号","इमोजी","Emojis","إيموجي","Émojis","ইমোজি","Emojis","Эмодзи","ایموجی","Emoji","Emojis","絵文字","Emoji","이모지","ایموجی","Емодзі","Emoji","Emoji","Emoji"],
  "Voice changer": ["变声器","वॉइस चेंजर","Cambiador de voz","مغيّر الصوت","Modulateur de voix","ভয়েস চেঞ্জার","Alterador de voz","Изменение голоса","وائس چینجر","Pengubah suara","Stimmverzerrer","ボイスチェンジャー","Ses değiştirici","음성 변조","تغییردهندهٔ صدا","Зміна голосу","Cambia voce","Zmieniacz głosu","Đổi giọng"],
  "Record yourself": ["录下你自己","खुद को रिकॉर्ड करें","Grábate","سجّل نفسك","Enregistre-toi","নিজেকে রেকর্ড করো","Grava-te","Запиши себя","خود کو ریکارڈ کریں","Rekam dirimu","Nimm dich auf","自分を録音する","Kendini kaydet","직접 녹음하기","خودت را ضبط کن","Запиши себе","Registrati","Nagraj siebie","Tự ghi âm"],
  "Simple": ["简单","सरल","Sencillo","بسيط","Simple","সহজ","Simples","Простой","سادہ","Sederhana","Einfach","かんたん","Basit","간단","ساده","Простий","Semplice","Prosty","Đơn giản"],
  "Complex": ["复杂","उन्नत","Avanzado","متقدّم","Avancé","উন্নত","Avançado","Расширенный","پیچیدہ","Lanjutan","Erweitert","詳細","Gelişmiş","고급","پیشرفته","Розширений","Avanzato","Zaawansowany","Nâng cao"],
  "Untitled Project": ["未命名项目","बिना नाम प्रोजेक्ट","Proyecto sin título","مشروع بلا عنوان","Projet sans titre","নামহীন প্রজেক্ট","Projeto sem título","Проект без названия","بے نام پروجیکٹ","Proyek tanpa judul","Unbenanntes Projekt","無題のプロジェクト","Adsız proje","제목 없는 프로젝트","پروژهٔ بی‌نام","Проєкт без назви","Progetto senza titolo","Projekt bez nazwy","Dự án chưa đặt tên"],
  "same media, separate cut": ["同一素材，独立剪辑","वही मीडिया, अलग कट","mismo medio, corte aparte","نفس الوسيط، قَصّ منفصل","même média, coupe distincte","একই মিডিয়া, আলাদা কাট","mesmo ficheiro, corte separado","тот же файл, отдельная нарезка","وہی میڈیا، الگ کٹ","media sama, potongan terpisah","dieselbe Datei, eigener Schnitt","同じ素材、別のカット","aynı medya, ayrı kesim","같은 소스, 별도 컷","همان رسانه، برش جدا","той самий файл, окремий монтаж","stesso media, taglio separato","to samo media, osobne cięcie","cùng media, cắt riêng"],
  "Help": ["帮助","मदद","Ayuda","مساعدة","Aide","সাহায্য","Ajuda","Помощь","مدد","Bantuan","Hilfe","ヘルプ","Yardım","도움말","راهنما","Довідка","Aiuto","Pomoc","Trợ giúp"],
  "Back to the site": ["返回网站","साइट पर वापस","Volver al sitio","العودة إلى الموقع","Retour au site","সাইটে ফিরে যাও","Voltar ao site","Назад на сайт","سائٹ پر واپس","Kembali ke situs","Zurück zur Website","サイトに戻る","Siteye dön","사이트로 돌아가기","بازگشت به سایت","Назад на сайт","Torna al sito","Powrót do strony","Quay lại trang"],
  "▶ Clip finder": ["▶ 片段查找","▶ क्लिप फ़ाइंडर","▶ Buscador de clips","▶ باحث المقاطع","▶ Chercheur de clips","▶ ক্লিপ ফাইন্ডার","▶ Localizador de clipes","▶ Поиск клипов","▶ کلپ فائنڈر","▶ Pencari klip","▶ Clip-Finder","▶ クリップ検索","▶ Klip bulucu","▶ 클립 찾기","▶ یابندهٔ کلیپ","▶ Пошук кліпів","▶ Trova clip","▶ Wyszukiwarka klipów","▶ Tìm clip"],
  "Clip": ["片段","क्लिप","Clip","مقطع","Clip","ক্লিপ","Clipe","Клип","کلپ","Klip","Clip","クリップ","Klip","클립","کلیپ","Кліп","Clip","Klip","Clip"],
  "Video": ["视频","वीडियो","Vídeo","فيديو","Vidéo","ভিডিও","Vídeo","Видео","ویڈیو","Video","Video","動画","Video","영상","ویدیو","Відео","Video","Wideo","Video"],

  /* ---- the Studio landing page ------------------------------------------ */
  "Creator Studio": ["创作者工作室","क्रिएटर स्टूडियो","Estudio del creador","استوديو صانع المحتوى","Studio du créateur","ক্রিয়েটর স্টুডিও","Estúdio do criador","Студия автора","کری ایٹر اسٹوڈیو","Studio kreator","Creator-Studio","クリエイタースタジオ","Üretici stüdyosu","크리에이터 스튜디오","استودیوی سازنده","Студія автора","Studio del creator","Studio twórcy","Xưởng của nhà sáng tạo"],
  "NovaClip Studio": ["NovaClip 工作室","NovaClip स्टूडियो","Estudio NovaClip","استوديو NovaClip","Studio NovaClip","NovaClip স্টুডিও","Estúdio NovaClip","Студия NovaClip","NovaClip اسٹوڈیو","Studio NovaClip","NovaClip Studio","NovaClip スタジオ","NovaClip Stüdyo","NovaClip 스튜디오","استودیوی NovaClip","Студія NovaClip","Studio NovaClip","Studio NovaClip","Xưởng NovaClip"],
  "Studio": ["工作室","स्टूडियो","Estudio","استوديو","Studio","স্টুডিও","Estúdio","Студия","اسٹوڈیو","Studio","Studio","スタジオ","Stüdyo","스튜디오","استودیو","Студія","Studio","Studio","Xưởng"],
  "Creator": ["创作者","क्रिएटर","Creador","صانع المحتوى","Créateur","ক্রিয়েটর","Criador","Автор","کری ایٹر","Kreator","Creator","クリエイター","Üretici","크리에이터","سازنده","Автор","Creator","Twórca","Nhà sáng tạo"],
  "Open Trend Spotter": ["打开趋势雷达","ट्रेंड स्पॉटर खोलें","Abrir el Detector de tendencias","افتح راصد الاتجاهات","Ouvrir le Détecteur de tendances","ট্রেন্ড স্পটার খোলো","Abrir o Detetor de tendências","Открыть «Тренд-радар»","ٹرینڈ اسپاٹر کھولیں","Buka Pemantau Tren","Trend-Spotter öffnen","トレンドスポッターを開く","Trend Bulucu'yu aç","트렌드 스포터 열기","ردیاب ترند را باز کن","Відкрити «Трендошукач»","Apri il Rilevatore di tendenze","Otwórz Wykrywacz trendów","Mở Dò xu hướng"],
  "Go to Trend Spotter": ["前往趋势雷达","ट्रेंड स्पॉटर पर जाएँ","Ir al Detector de tendencias","اذهب إلى راصد الاتجاهات","Aller au Détecteur de tendances","ট্রেন্ড স্পটারে যাও","Ir para o Detetor de tendências","Перейти к «Тренд-радару»","ٹرینڈ اسپاٹر پر جائیں","Ke Pemantau Tren","Zum Trend-Spotter","トレンドスポッターへ","Trend Bulucu'ya git","트렌드 스포터로 가기","به ردیاب ترند برو","До «Трендошукача»","Vai al Rilevatore di tendenze","Przejdź do Wykrywacza trendów","Tới Dò xu hướng"],
  "Trend Spotter": ["趋势雷达","ट्रेंड स्पॉटर","Detector de tendencias","راصد الاتجاهات","Détecteur de tendances","ট্রেন্ড স্পটার","Detetor de tendências","Тренд-радар","ٹرینڈ اسپاٹر","Pemantau Tren","Trend-Spotter","トレンドスポッター","Trend Bulucu","트렌드 스포터","ردیاب ترند","Трендошукач","Rilevatore di tendenze","Wykrywacz trendów","Dò xu hướng"],
  "Nova Points": ["Nova 积分","Nova पॉइंट","Puntos Nova","نقاط Nova","Points Nova","Nova পয়েন্ট","Pontos Nova","Очки Nova","Nova پوائنٹس","Poin Nova","Nova-Punkte","Nova ポイント","Nova puanı","Nova 포인트","امتیاز Nova","Бали Nova","Punti Nova","Punkty Nova","Điểm Nova"],
  "Trend Scans": ["趋势扫描","ट्रेंड स्कैन","Escaneos de tendencias","مسح الاتجاهات","Scans de tendances","ট্রেন্ড স্ক্যান","Análises de tendências","Сканы трендов","ٹرینڈ اسکینز","Pindaian tren","Trend-Scans","トレンドスキャン","Trend taramaları","트렌드 스캔","اسکن ترند","Скани трендів","Scansioni di tendenze","Skany trendów","Lượt quét xu hướng"],
  "Pipeline Steps": ["流程步骤","पाइपलाइन चरण","Pasos del flujo","خطوات المسار","Étapes du flux","পাইপলাইন ধাপ","Passos do fluxo","Шаги конвейера","پائپ لائن مراحل","Langkah alur","Pipeline-Schritte","パイプラインの手順","Akış adımları","파이프라인 단계","گام‌های خط تولید","Кроки конвеєра","Fasi del flusso","Kroki procesu","Các bước quy trình"],
  "Creator pipeline": ["创作流程","क्रिएटर पाइपलाइन","Flujo del creador","مسار صانع المحتوى","Flux du créateur","ক্রিয়েটর পাইপলাইন","Fluxo do criador","Конвейер автора","کری ایٹر پائپ لائن","Alur kreator","Creator-Pipeline","クリエイターの流れ","Üretici akışı","크리에이터 파이프라인","خط تولید سازنده","Конвеєр автора","Flusso del creator","Proces twórcy","Quy trình sáng tạo"],
  "Find what to make before it peaks.": ["在爆火之前就知道该做什么。","चरम पर पहुँचने से पहले जानें क्या बनाना है।","Descubre qué hacer antes de que explote.","اعرف ما تصنعه قبل أن يبلغ ذروته.","Trouve quoi faire avant que ça explose.","চূড়ায় ওঠার আগেই জেনে নাও কী বানাবে।","Descobre o que fazer antes de rebentar.","Узнай, что снимать, до пика.","عروج سے پہلے جانیں کیا بنانا ہے۔","Tahu harus bikin apa sebelum memuncak.","Finde heraus, was angesagt wird, bevor es das ist.","ピークが来る前に、作るものを見つける。","Zirveye çıkmadan ne çekeceğini bul.","정점에 오르기 전에 무엇을 만들지 찾기.","پیش از اوج گرفتن، بفهم چه بسازی.","Дізнайся, що знімати, до піку.","Scopri cosa fare prima che esploda.","Dowiedz się, co robić, zanim wystrzeli.","Biết nên làm gì trước khi nó bùng nổ."],
  "Video Ideas": ["视频创意","वीडियो आइडिया","Ideas de vídeo","أفكار فيديو","Idées de vidéos","ভিডিও আইডিয়া","Ideias de vídeo","Идеи для видео","ویڈیو آئیڈیاز","Ide video","Videoideen","動画のアイデア","Video fikirleri","영상 아이디어","ایده‌های ویدیو","Ідеї для відео","Idee video","Pomysły na filmy","Ý tưởng video"],
  "Titles, hooks and formats to steal the feed.": ["抢占信息流的标题、钩子和形式。","फ़ीड पर छा जाने वाले टाइटल, हुक और फ़ॉर्मेट।","Títulos, ganchos y formatos para arrasar en el feed.","عناوين وخطّافات وصيغ تخطف الواجهة.","Titres, accroches et formats pour rafler le fil.","ফিড দখল করার টাইটেল, হুক আর ফরম্যাট।","Títulos, ganchos e formatos para dominar o feed.","Заголовки, зацепки и форматы, чтобы забрать ленту.","فیڈ پر چھا جانے والے ٹائٹل، ہُک اور فارمیٹ۔","Judul, pancingan, dan format untuk merebut feed.","Titel, Hooks und Formate, die den Feed holen.","フィードを奪うタイトル・フック・フォーマット。","Akışı kapan başlıklar, kancalar ve formatlar.","피드를 가져올 제목과 후킹, 포맷.","عنوان، قلاب و قالبی که فید را می‌قاپد.","Заголовки, гачки й формати, щоб забрати стрічку.","Titoli, hook e formati per prendersi il feed.","Tytuły, haczyki i formaty, które zgarną feed.","Tiêu đề, cú móc và định dạng để chiếm feed."],
  "Scripts": ["脚本","स्क्रिप्ट","Guiones","نصوص","Scripts","স্ক্রিপ্ট","Guiões","Сценарии","اسکرپٹس","Naskah","Skripte","台本","Senaryolar","대본","فیلمنامه‌ها","Сценарії","Copioni","Scenariusze","Kịch bản"],
  "Turn a trend into a full script.": ["把一个趋势变成完整脚本。","एक ट्रेंड को पूरी स्क्रिप्ट में बदलें।","Convierte una tendencia en un guion completo.","حوّل اتجاهًا إلى نص كامل.","Transforme une tendance en script complet.","একটা ট্রেন্ডকে পুরো স্ক্রিপ্টে বদলে নাও।","Transforma uma tendência num guião completo.","Преврати тренд в полный сценарий.","ایک ٹرینڈ کو مکمل اسکرپٹ بنائیں۔","Ubah satu tren jadi naskah utuh.","Mach aus einem Trend ein ganzes Skript.","トレンドを台本一本に変える。","Bir trendi tam senaryoya çevir.","트렌드 하나를 완성된 대본으로.","یک ترند را به فیلمنامهٔ کامل تبدیل کن.","Перетвори тренд на повний сценарій.","Trasforma una tendenza in un copione completo.","Zamień trend w pełny scenariusz.","Biến một xu hướng thành kịch bản đầy đủ."],
  "Thumbnails": ["缩略图","थंबनेल","Miniaturas","صور مصغّرة","Miniatures","থাম্বনেইল","Miniaturas","Обложки","تھمب نیلز","Thumbnail","Thumbnails","サムネイル","Küçük resimler","썸네일","بندانگشتی‌ها","Обкладинки","Miniature","Miniatury","Ảnh thu nhỏ"],
  "Click-through thumbnails that convert.": ["让人忍不住点的缩略图。","क्लिक करवाने वाले थंबनेल।","Miniaturas que se hacen clic.","صور مصغّرة تدفع للنقر.","Des miniatures qui font cliquer.","যেসব থাম্বনেইলে ক্লিক পড়ে।","Miniaturas que levam ao clique.","Обложки, на которые кликают.","کلک کرانے والے تھمب نیل۔","Thumbnail yang bikin diklik.","Thumbnails, auf die geklickt wird.","クリックされるサムネイル。","Tıklatan küçük resimler.","클릭을 부르는 썸네일.","بندانگشتی‌هایی که کلیک می‌گیرند.","Обкладинки, на які клікають.","Miniature su cui si clicca.","Miniatury, w które się klika.","Ảnh thu nhỏ khiến người ta bấm."],
  "Editor": ["剪辑器","एडिटर","Editor","المحرر","Éditeur","এডিটর","Editor","Редактор","ایڈیٹر","Editor","Editor","エディター","Düzenleyici","편집기","ویرایشگر","Редактор","Editor","Edytor","Trình biên tập"],
  "Cut, pace and package your video.": ["剪辑、把握节奏、包装你的视频。","अपने वीडियो को काटें, लय दें और सजाएँ।","Corta, marca el ritmo y empaqueta tu vídeo.","قُصّ وأضبط الإيقاع وغلّف الفيديو.","Coupe, rythme et habille ta vidéo.","ভিডিও কাটো, গতি দাও, সাজাও।","Corta, dá ritmo e embala o teu vídeo.","Нарежь, задай темп и упакуй видео.","اپنی ویڈیو کاٹیں، رفتار دیں اور سجائیں۔","Potong, atur tempo, dan kemas videomu.","Schneide, takte und verpacke dein Video.","動画を切って、テンポをつけて、仕上げる。","Videonu kes, ritmini ayarla, paketle.","영상을 자르고 흐름을 잡고 포장하기.","ویدیو را ببر، ریتم بده و بسته‌بندی کن.","Наріж, задай темп і запакуй відео.","Taglia, dai ritmo e confeziona il video.","Potnij, nadaj tempo i opakuj film.","Cắt, tạo nhịp và đóng gói video."],
  "Ship to every platform at once.": ["一次发布到所有平台。","एक बार में हर प्लैटफ़ॉर्म पर भेजें।","Publica en todas las plataformas a la vez.","انشر على كل المنصات دفعة واحدة.","Publie partout d'un seul coup.","একবারে সব প্ল্যাটফর্মে পাঠাও।","Publica em todas as plataformas de uma vez.","Опубликуй сразу на всех площадках.","ایک ہی بار میں ہر پلیٹ فارم پر بھیجیں۔","Kirim ke semua platform sekaligus.","Auf einen Schlag überall veröffentlichen.","すべてのプラットフォームへ一度に。","Hepsine aynı anda gönder.","모든 플랫폼에 한 번에 올리기.","یک‌باره روی همهٔ پلتفرم‌ها منتشر کن.","Опублікуй одразу всюди.","Pubblica su ogni piattaforma in una volta.","Wyślij na wszystkie platformy naraz.","Đăng lên mọi nền tảng cùng lúc."],
  "Jump back into a niche you already scanned.": ["回到你扫描过的领域。","जिस निच को पहले स्कैन किया था, उसमें लौटें।","Vuelve a un nicho que ya escaneaste.","عُد إلى مجال سبق أن مسحته.","Reviens sur une niche déjà scannée.","আগেই স্ক্যান করা নিশে ফিরে যাও।","Volta a um nicho que já analisaste.","Вернись к нише, которую уже сканировал.","جو نِچ پہلے اسکین کیا، اس پر واپس جائیں۔","Kembali ke niche yang sudah kamu pindai.","Zurück in eine Nische, die du schon gescannt hast.","すでにスキャンしたニッチに戻る。","Daha önce taradığın bir alana dön.","이미 스캔한 분야로 돌아가기.","به حوزه‌ای که قبلاً اسکن کردی برگرد.","Повернись до ніші, яку вже сканував.","Torna su una nicchia che hai già scansionato.","Wróć do niszy, którą już skanowałeś.","Quay lại ngách bạn đã quét."],

  /* ---- the games ------------------------------------------------------- */
  "Time": ["时间","समय","Tiempo","الوقت","Temps","সময়","Tempo","Время","وقت","Waktu","Zeit","タイム","Süre","시간","زمان","Час","Tempo","Czas","Thời gian"],
  "Hits": ["命中","हिट","Aciertos","إصابات","Touchés","হিট","Acertos","Попадания","ہٹس","Kena","Treffer","ヒット","İsabet","적중","اصابت","Влучання","Colpi","Trafienia","Trúng"],
  "Misses": ["未命中","मिस","Fallos","إخفاقات","Ratés","মিস","Falhas","Промахи","مِسز","Meleset","Fehlschüsse","ミス","Iska","빗나감","خطا","Промахи","Errori","Pudła","Trượt"],
  "Score": ["得分","स्कोर","Puntuación","النتيجة","Score","স্কোর","Pontuação","Счёт","اسکور","Skor","Punktzahl","スコア","Skor","점수","امتیاز","Рахунок","Punteggio","Wynik","Điểm"],
  "Accuracy": ["准确率","सटीकता","Precisión","الدقّة","Précision","নির্ভুলতা","Precisão","Точность","درستگی","Akurasi","Genauigkeit","正確率","İsabet oranı","정확도","دقت","Точність","Precisione","Celność","Độ chính xác"],
  "Ready?": ["准备好了吗？","तैयार?","¿Listo?","جاهز؟","Prêt ?","তৈরি?","Pronto?","Готов?","تیار؟","Siap?","Bereit?","準備はいい？","Hazır mısın?","준비됐나요?","آماده‌ای؟","Готовий?","Pronto?","Gotowy?","Sẵn sàng chưa?"],
  "Points": ["积分","पॉइंट","Puntos","النقاط","Points","পয়েন্ট","Pontos","Очки","پوائنٹس","Poin","Punkte","ポイント","Puan","포인트","امتیاز","Бали","Punti","Punkty","Điểm"],
  "Press to start": ["按下开始","शुरू करने के लिए दबाएँ","Pulsa para empezar","اضغط للبدء","Appuie pour commencer","শুরু করতে চাপো","Carrega para começar","Нажми, чтобы начать","شروع کرنے کے لیے دبائیں","Tekan untuk mulai","Zum Start drücken","押してスタート","Başlamak için bas","눌러서 시작","برای شروع بزن","Натисни, щоб почати","Premi per iniziare","Naciśnij, aby zacząć","Nhấn để bắt đầu"],
  "Start": ["开始","शुरू","Empezar","ابدأ","Démarrer","শুরু","Começar","Старт","شروع","Mulai","Start","スタート","Başla","시작","شروع","Старт","Inizia","Start","Bắt đầu"],
  "Target": ["靶心","टारगेट","Diana","الهدف","Cible","টার্গেট","Alvo","Мишень","ٹارگٹ","Target","Ziel","ターゲット","Hedef","타깃","هدف","Ціль","Bersaglio","Cel","Mục tiêu"],
  "Reaction": ["反应","रिएक्शन","Reacción","رد الفعل","Réaction","রিঅ্যাকশন","Reação","Реакция","ری ایکشن","Reaksi","Reaktion","反応速度","Tepki","반응속도","واکنش","Реакція","Reazione","Refleks","Phản xạ"],
  "Median of five": ["五次中位数","पाँच का माध्यिका","Mediana de cinco","وسيط خمس محاولات","Médiane sur cinq","পাঁচটির মধ্যমা","Mediana de cinco","Медиана из пяти","پانچ کا میڈین","Median dari lima","Median aus fünf","5回の中央値","Beşin ortancası","다섯 번의 중앙값","میانهٔ پنج","Медіана з п'яти","Mediana di cinque","Mediana z pięciu","Trung vị của năm"],
  "Fastest single go": ["单次最快","सबसे तेज़ एक बार","El intento más rápido","أسرع محاولة واحدة","Meilleur essai","সবচেয়ে দ্রুত একটি","A tentativa mais rápida","Самая быстрая попытка","سب سے تیز ایک کوشش","Percobaan tercepat","Schnellster Einzelversuch","最速の1回","En hızlı tek deneme","가장 빠른 한 번","سریع‌ترین تک‌تلاش","Найшвидша спроба","Il tentativo più veloce","Najszybsza próba","Lần nhanh nhất"],
  "Space": ["空格","स्पेस","Espacio","مسافة","Espace","স্পেস","Espaço","Пробел","اسپیس","Spasi","Leertaste","スペース","Boşluk","스페이스","فاصله","Пробіл","Spazio","Spacja","Phím cách"],
  "tap": ["点击","टैप","toca","انقر","appuie","ট্যাপ","toca","тап","ٹیپ","ketuk","tippen","タップ","dokun","탭","ضربه","тап","tocca","dotknij","chạm"],
  "Typing race": ["打字竞速","टाइपिंग रेस","Carrera de escritura","سباق الكتابة","Course de frappe","টাইপিং রেস","Corrida de escrita","Гонка на печать","ٹائپنگ ریس","Balapan mengetik","Tipp-Rennen","タイピングレース","Yazma yarışı","타자 경주","مسابقهٔ تایپ","Перегони з набору","Gara di battitura","Wyścig pisania","Đua gõ phím"],
  "Nova Flap": ["Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap","Nova Flap"],
  "Leaderboard": ["排行榜","लीडरबोर्ड","Clasificación","لوحة الصدارة","Classement","লিডারবোর্ড","Classificação","Таблица лидеров","لیڈر بورڈ","Papan peringkat","Bestenliste","ランキング","Sıralama","리더보드","جدول صدرنشینان","Таблиця лідерів","Classifica","Ranking","Bảng xếp hạng"],
  "Profile": ["个人资料","प्रोफ़ाइल","Perfil","الملف الشخصي","Profil","প্রোফাইল","Perfil","Профиль","پروفائل","Profil","Profil","プロフィール","Profil","프로필","پروفایل","Профіль","Profilo","Profil","Hồ sơ"],
  "Home": ["主页","होम","Inicio","الرئيسية","Accueil","হোম","Início","Главная","ہوم","Beranda","Start","ホーム","Ana sayfa","홈","خانه","Головна","Home","Start","Trang chủ"],
  "Play": ["开始玩","खेलें","Jugar","العب","Jouer","খেলো","Jogar","Играть","کھیلیں","Main","Spielen","プレイ","Oyna","플레이","بازی","Грати","Gioca","Graj","Chơi"],
  "Modes": ["模式","मोड","Modos","الأنماط","Modes","মোড","Modos","Режимы","موڈز","Mode","Modi","モード","Modlar","모드","حالت‌ها","Режими","Modalità","Tryby","Chế độ"],
  "Challenges": ["挑战","चैलेंज","Retos","التحديات","Défis","চ্যালেঞ্জ","Desafios","Испытания","چیلنجز","Tantangan","Challenges","チャレンジ","Meydan okumalar","챌린지","چالش‌ها","Виклики","Sfide","Wyzwania","Thử thách"],
  "Stats": ["数据","आँकड़े","Estadísticas","إحصاءات","Stats","পরিসংখ্যান","Estatísticas","Статистика","اعداد و شمار","Statistik","Statistiken","統計","İstatistik","통계","آمار","Статистика","Statistiche","Statystyki","Thống kê"],
  "Guest": ["访客","मेहमान","Invitado","ضيف","Invité","অতিথি","Convidado","Гость","مہمان","Tamu","Gast","ゲスト","Misafir","손님","مهمان","Гість","Ospite","Gość","Khách"],
  "Today": ["今天","आज","Hoy","اليوم","Aujourd'hui","আজ","Hoje","Сегодня","آج","Hari ini","Heute","今日","Bugün","오늘","امروز","Сьогодні","Oggi","Dziś","Hôm nay"],
  "Week": ["本周","सप्ताह","Semana","أسبوع","Semaine","সপ্তাহ","Semana","Неделя","ہفتہ","Minggu","Woche","週","Hafta","주","هفته","Тиждень","Settimana","Tydzień","Tuần"],
  "Month": ["本月","महीना","Mes","شهر","Mois","মাস","Mês","Месяц","مہینہ","Bulan","Monat","月","Ay","월","ماه","Місяць","Mese","Miesiąc","Tháng"],
  "Year": ["全年","साल","Año","سنة","Année","বছর","Ano","Год","سال","Tahun","Jahr","年","Yıl","연","سال","Рік","Anno","Rok","Năm"],

  /* ---- the Coder page --------------------------------------------------- */
  "Coder": ["编码器","कोडर","Programador","المبرمج","Codeur","কোডার","Programador","Кодер","کوڈر","Coder","Coder","コーダー","Kodlayıcı","코더","کدنویس","Кодер","Coder","Koder","Lập trình"],
  "What do you want built?": ["你想让它做什么？","आप क्या बनवाना चाहते हैं?","¿Qué quieres que te construya?","ماذا تريد أن نبني؟","Tu veux qu'on construise quoi ?","তুমি কী বানাতে চাও?","O que queres que seja construído?","Что построить?","آپ کیا بنوانا چاہتے ہیں؟","Mau dibuatkan apa?","Was soll gebaut werden?","何を作りますか？","Ne inşa edelim?","무엇을 만들까요?","می‌خواهی چه چیزی ساخته شود؟","Що побудувати?","Cosa vuoi che venga costruito?","Co mamy zbudować?","Bạn muốn dựng gì?"],
  "Build it": ["开始构建","बनाओ","Constrúyelo","ابنِه","Construire","বানাও","Construir","Построить","بنائیں","Buat","Bauen","作る","İnşa et","만들기","بسازش","Побудувати","Costruisci","Zbuduj","Dựng"],
  "✓ Things it can build": ["✓ 它能做的","✓ जो यह बना सकता है","✓ Lo que sí puede construir","✓ ما يستطيع بناءه","✓ Ce qu'il sait construire","✓ যা এটি বানাতে পারে","✓ O que consegue construir","✓ Что он может построить","✓ جو یہ بنا سکتا ہے","✓ Yang bisa dibuat","✓ Was es bauen kann","✓ 作れるもの","✓ Yapabildikleri","✓ 만들 수 있는 것","✓ آنچه می‌تواند بسازد","✓ Що він може зробити","✓ Cosa sa costruire","✓ Co potrafi zbudować","✓ Những thứ nó dựng được"],
  "✕ Things it will refuse, and say so": ["✕ 它会拒绝，并直说","✕ जो यह मना करेगा, और बता देगा","✕ Lo que rechazará, y lo dirá","✕ ما سيرفضه، وسيقولها","✕ Ce qu'il refusera, et le dira","✕ যা এটি করবে না, এবং বলে দেবে","✕ O que vai recusar, e dizer","✕ Что он откажется делать и так и скажет","✕ جو یہ نہیں کرے گا، اور بتا دے گا","✕ Yang akan ditolak, dan dikatakan","✕ Was es ablehnt — und das sagt","✕ 断るもの、そしてそう言う","✕ Reddedecekleri, ve söyleyecekleri","✕ 거절할 것, 그리고 그렇게 말할 것","✕ آنچه رد می‌کند و می‌گوید","✕ Від чого відмовиться — і скаже про це","✕ Cosa rifiuterà, dicendolo","✕ Czego odmówi — i powie o tym","✕ Những thứ nó từ chối, và nói thẳng"],
  "Animated lower thirds and end screens": ["动态字幕条和片尾画面","एनिमेटेड लोअर थर्ड और एंड स्क्रीन","Rótulos animados y pantallas finales","أشرطة سفلية متحركة وشاشات ختامية","Bandeaux animés et écrans de fin","অ্যানিমেটেড লোয়ার থার্ড ও এন্ড স্ক্রিন","Oráculos animados e ecrãs finais","Анимированные титры и конечные заставки","اینیمیٹڈ لوئر تھرڈ اور اینڈ اسکرینز","Lower third animasi dan layar penutup","Animierte Bauchbinden und Endscreens","アニメーションのテロップとエンドカード","Animasyonlu alt bantlar ve bitiş ekranları","애니메이션 자막 바와 엔드 화면","نوار پایین متحرک و صفحهٔ پایانی","Анімовані титри та кінцеві екрани","Sottopancia animati e schermate finali","Animowane belki i ekrany końcowe","Thanh chữ động và màn hình kết"],
  "A landing page for your channel links": ["放你频道链接的落地页","आपके चैनल लिंक के लिए लैंडिंग पेज","Una página con los enlaces de tu canal","صفحة هبوط لروابط قناتك","Une page d'accueil pour tes liens","তোমার চ্যানেল লিংকের ল্যান্ডিং পেজ","Uma página com os links do teu canal","Лендинг со ссылками твоего канала","آپ کے چینل لنکس کے لیے لینڈنگ پیج","Halaman untuk semua tautan kanalmu","Eine Landingpage für deine Kanal-Links","チャンネルのリンクをまとめたページ","Kanal bağlantıların için bir açılış sayfası","채널 링크를 모은 랜딩 페이지","صفحهٔ فرود برای لینک‌های کانالت","Лендинг із посиланнями твого каналу","Una pagina con i link del tuo canale","Strona z linkami twojego kanału","Trang đích cho các liên kết kênh"],
  "Thumbnail templates you fill in and screenshot": ["填好再截图的缩略图模板","थंबनेल टेम्पलेट जो भरकर स्क्रीनशॉट लें","Plantillas de miniatura que rellenas y capturas","قوالب صور مصغّرة تملؤها ثم تلتقطها","Des modèles de miniatures à remplir et capturer","থাম্বনেইল টেমপ্লেট — পূরণ করে স্ক্রিনশট নাও","Modelos de miniatura que preenches e capturas","Шаблоны обложек: заполни и сделай скриншот","تھمب نیل ٹیمپلیٹس جو بھر کر اسکرین شاٹ لیں","Templat thumbnail yang kamu isi lalu tangkap layar","Thumbnail-Vorlagen zum Ausfüllen und Abfotografieren","書き込んでスクショするサムネのひな形","Doldurup ekran görüntüsü aldığın küçük resim şablonları","채워서 캡처하는 썸네일 템플릿","قالب بندانگشتی که پر می‌کنی و اسکرین‌شات می‌گیری","Шаблони обкладинок: заповни і зроби скриншот","Modelli di miniatura da riempire e catturare","Szablony miniatur do wypełnienia i zrzutu","Mẫu ảnh thu nhỏ bạn điền rồi chụp màn hình"],
  "Small games and widgets for your community": ["给你社群的小游戏和小组件","आपकी कम्युनिटी के लिए छोटे गेम और विजेट","Juegos y widgets pequeños para tu comunidad","ألعاب صغيرة وأدوات لمجتمعك","Petits jeux et widgets pour ta communauté","তোমার কমিউনিটির জন্য ছোট গেম ও উইজেট","Jogos pequenos e widgets para a tua comunidade","Мини-игры и виджеты для твоего сообщества","آپ کی کمیونٹی کے لیے چھوٹے گیمز اور وجٹس","Gim kecil dan widget untuk komunitasmu","Kleine Spiele und Widgets für deine Community","コミュニティ向けの小さなゲームやウィジェット","Topluluğun için küçük oyunlar ve araçlar","커뮤니티용 작은 게임과 위젯","بازی‌های کوچک و ابزارک برای جامعه‌ات","Міні-ігри та віджети для твоєї спільноти","Piccoli giochi e widget per la tua community","Małe gry i widżety dla twojej społeczności","Trò chơi nhỏ và tiện ích cho cộng đồng"],
  "Anything with a server, a database or a login": ["任何需要服务器、数据库或登录的东西","कुछ भी जिसमें सर्वर, डेटाबेस या लॉगिन हो","Cualquier cosa con servidor, base de datos o inicio de sesión","أي شيء فيه خادم أو قاعدة بيانات أو تسجيل دخول","Tout ce qui a un serveur, une base ou une connexion","সার্ভার, ডেটাবেস বা লগইন লাগে এমন কিছু","Qualquer coisa com servidor, base de dados ou login","Всё, где нужен сервер, база данных или вход","کوئی بھی چیز جس میں سرور، ڈیٹابیس یا لاگ اِن ہو","Apa pun yang perlu server, basis data, atau login","Alles mit Server, Datenbank oder Login","サーバー・データベース・ログインが要るもの","Sunucu, veritabanı veya giriş gerektiren her şey","서버, 데이터베이스, 로그인이 필요한 것","هر چیزی که سرور، پایگاه‌داده یا ورود بخواهد","Усе, де потрібен сервер, база даних чи вхід","Qualsiasi cosa con server, database o login","Cokolwiek z serwerem, bazą danych lub logowaniem","Bất cứ thứ gì cần máy chủ, cơ sở dữ liệu hay đăng nhập"],
  "Getting into an account that is not yours": ["登入不属于你的账号","किसी और के अकाउंट में घुसना","Entrar en una cuenta que no es tuya","الدخول إلى حساب ليس لك","Entrer dans un compte qui n'est pas le tien","তোমার নয় এমন অ্যাকাউন্টে ঢোকা","Entrar numa conta que não é tua","Вход в чужой аккаунт","کسی اور کے اکاؤنٹ میں داخل ہونا","Masuk ke akun yang bukan milikmu","In ein fremdes Konto kommen","自分のものでないアカウントに入ること","Sana ait olmayan bir hesaba girmek","남의 계정에 들어가기","ورود به حسابی که مال تو نیست","Вхід у чужий обліковий запис","Entrare in un account non tuo","Wchodzenie na cudze konto","Vào tài khoản không phải của bạn"],
  "Downloading videos that are not yours": ["下载不属于你的视频","दूसरों के वीडियो डाउनलोड करना","Descargar vídeos que no son tuyos","تنزيل فيديوهات ليست لك","Télécharger des vidéos qui ne sont pas les tiennes","তোমার নয় এমন ভিডিও ডাউনলোড করা","Descarregar vídeos que não são teus","Скачивание чужих видео","دوسروں کی ویڈیوز ڈاؤن لوڈ کرنا","Mengunduh video yang bukan milikmu","Fremde Videos herunterladen","自分のものでない動画をダウンロードすること","Sana ait olmayan videoları indirmek","남의 영상 내려받기","دانلود ویدیوهایی که مال تو نیستند","Завантаження чужих відео","Scaricare video non tuoi","Pobieranie cudzych filmów","Tải video không phải của bạn"],

  /* ---- the analytics tiles, which every channel page repeats ------------- */
  "Views": ["观看次数","व्यूज़","Visualizaciones","المشاهدات","Vues","ভিউ","Visualizações","Просмотры","ویوز","Penayangan","Aufrufe","再生回数","Görüntülenme","조회수","بازدید","Перегляди","Visualizzazioni","Wyświetlenia","Lượt xem"],
  "Subscribers": ["订阅者","सब्सक्राइबर","Suscriptores","المشتركون","Abonnés","সাবস্ক্রাইবার","Subscritores","Подписчики","سبسکرائبرز","Pelanggan","Abonnenten","登録者","Aboneler","구독자","دنبال‌کننده","Підписники","Iscritti","Subskrybenci","Người đăng ký"],
  "Videos": ["视频数","वीडियो","Vídeos","الفيديوهات","Vidéos","ভিডিও","Vídeos","Видео","ویڈیوز","Video","Videos","動画数","Videolar","영상","ویدیوها","Відео","Video","Filmy","Video"],
  "Total views": ["总观看次数","कुल व्यूज़","Visualizaciones totales","إجمالي المشاهدات","Vues totales","মোট ভিউ","Visualizações totais","Всего просмотров","کل ویوز","Total penayangan","Aufrufe insgesamt","総再生回数","Toplam görüntülenme","총 조회수","کل بازدید","Усього переглядів","Visualizzazioni totali","Łączne wyświetlenia","Tổng lượt xem"],
  "Your channel": ["你的频道","आपका चैनल","Tu canal","قناتك","Ta chaîne","তোমার চ্যানেল","O teu canal","Твой канал","آپ کا چینل","Kanalmu","Dein Kanal","あなたのチャンネル","Kanalın","내 채널","کانال تو","Твій канал","Il tuo canale","Twój kanał","Kênh của bạn"],
  "Last 28 days": ["最近 28 天","पिछले 28 दिन","Últimos 28 días","آخر 28 يومًا","28 derniers jours","গত ২৮ দিন","Últimos 28 dias","Последние 28 дней","پچھلے 28 دن","28 hari terakhir","Letzte 28 Tage","直近28日","Son 28 gün","최근 28일","۲۸ روز گذشته","Останні 28 днів","Ultimi 28 giorni","Ostatnie 28 dni","28 ngày qua"],
  "Performance": ["表现","प्रदर्शन","Rendimiento","الأداء","Performances","পারফরম্যান্স","Desempenho","Показатели","کارکردگی","Performa","Leistung","パフォーマンス","Performans","성과","عملکرد","Показники","Rendimento","Wyniki","Hiệu suất"],
  "Compare": ["对比","तुलना करें","Comparar","قارن","Comparer","তুলনা করো","Comparar","Сравнить","موازنہ کریں","Bandingkan","Vergleichen","比較する","Karşılaştır","비교하기","مقایسه کن","Порівняти","Confronta","Porównaj","So sánh"],
  "Top countries": ["主要国家/地区","शीर्ष देश","Países principales","أهم البلدان","Principaux pays","শীর্ষ দেশ","Principais países","Основные страны","سرفہرست ممالک","Negara teratas","Top-Länder","上位の国","En çok ülkeler","상위 국가","کشورهای برتر","Основні країни","Paesi principali","Główne kraje","Quốc gia hàng đầu"],
  "Who is watching": ["谁在看","कौन देख रहा है","Quién te ve","من يشاهد","Qui regarde","কে দেখছে","Quem está a ver","Кто смотрит","کون دیکھ رہا ہے","Siapa yang menonton","Wer zuschaut","誰が見ているか","Kim izliyor","누가 보고 있는가","چه کسی تماشا می‌کند","Хто дивиться","Chi ti guarda","Kto ogląda","Ai đang xem"],
  "Channel review": ["频道复盘","चैनल समीक्षा","Revisión del canal","مراجعة القناة","Bilan de la chaîne","চ্যানেল পর্যালোচনা","Revisão do canal","Разбор канала","چینل جائزہ","Tinjauan kanal","Kanal-Rückblick","チャンネル診断","Kanal değerlendirmesi","채널 리뷰","مرور کانال","Огляд каналу","Analisi del canale","Przegląd kanału","Đánh giá kênh"],
  "Fair Fight": ["公平对决","फेयर फ़ाइट","Duelo justo","مواجهة عادلة","Duel équitable","ফেয়ার ফাইট","Duelo justo","Честный бой","فیئر فائٹ","Duel Adil","Fairer Vergleich","フェアファイト","Adil Karşılaşma","공정 대결","نبرد منصفانه","Чесний бій","Sfida equa","Uczciwy pojedynek","Đấu công bằng"],

  /* ---- the analytics consent strip, which is on every page --------------- */
  "Yes, that is fine": ["可以，没问题","हाँ, ठीक है","Sí, de acuerdo","نعم، لا بأس","Oui, d'accord","হ্যাঁ, ঠিক আছে","Sim, tudo bem","Да, хорошо","ہاں، ٹھیک ہے","Ya, boleh","Ja, ist in Ordnung","はい、かまいません","Evet, olur","네, 괜찮아요","بله، اشکالی ندارد","Так, гаразд","Sì, va bene","Tak, w porządku","Được, không sao"],
  "No thanks": ["不用了","नहीं, धन्यवाद","No, gracias","لا، شكرًا","Non merci","না, ধন্যবাদ","Não, obrigado","Нет, спасибо","نہیں، شکریہ","Tidak, terima kasih","Nein, danke","いいえ、結構です","Hayır, teşekkürler","괜찮습니다","نه، ممنون","Ні, дякую","No, grazie","Nie, dziękuję","Không, cảm ơn"],
  "What it records": ["它记录了什么","यह क्या रिकॉर्ड करता है","Qué registra","ما الذي يسجّله","Ce qu'il enregistre","এটি কী রেকর্ড করে","O que regista","Что он записывает","یہ کیا ریکارڈ کرتا ہے","Apa yang dicatat","Was aufgezeichnet wird","何を記録するか","Neyi kaydediyor","무엇을 기록하는지","چه چیزی ثبت می‌کند","Що він записує","Cosa registra","Co zapisuje","Nó ghi lại gì"],
  "Classic": ["经典","क्लासिक","Clásico","كلاسيكي","Classique","ক্লাসিক","Clássico","Классика","کلاسک","Klasik","Klassisch","クラシック","Klasik","클래식","کلاسیک","Класика","Classico","Klasyczny","Cổ điển"]

  };

  var out = {}, k, i, o;
  for (k in R) {
    if (!Object.prototype.hasOwnProperty.call(R, k)) continue;
    o = { en: k };
    for (i = 0; i < L.length; i++) o[L[i]] = R[k][i];
    out[k] = o;
  }
  window.NC_PHRASES = out;
  /* nova.js may have run its first translation pass before this file landed,
     so tell it to run another one. It is idempotent. */
  if (typeof window.ncRephrase === 'function') window.ncRephrase();
})();
