const THEMES = { 'Dark':['#0E1117','#1E2130','#FAFAFA'], 'Light':['#FFFFFF','#F0F2F6','#111111'], 'Blue':['#0A1A3F','#14295E','#D6E4FF'], 'Red':['#2B0A0A','#4A1414','#FFD6D6'], 'Green':['#0A2B14','#14472A','#D6FFE0'], 'Rainbow':['#1A0A2B','#2B1450','#FFFFFF'], 'Rainy Window':['#0B1016','#161E28','#D8E4F0'] };
const LANGS = { en:'English', zh:'中文', hi:'हिन्दी', es:'Español', ar:'العربية', fr:'Français', bn:'বাংলা', pt:'Português', ru:'Русский', ur:'اردو', id:'Bahasa Indonesia', de:'Deutsch', ja:'日本語', tr:'Türkçe', ko:'한국어', fa:'فارسی', uk:'Українська', it:'Italiano', pl:'Polski', vi:'Tiếng Việt' };
const RTL = ["ar", "fa", "ur"];
const T = {
  home: { en:"Home", zh:"首页", hi:"होम", es:"Inicio", ar:"الرئيسية", fr:"Accueil", bn:"হোম", pt:"Início", ru:"Главная", ur:"ہوم", id:"Beranda", de:"Start", ja:"ホーム", tr:"Ana Sayfa", ko:"홈", fa:"خانه", uk:"Головна", it:"Home", pl:"Start", vi:"Trang chủ" },
  studio: { en:"Studio", zh:"工作室", hi:"स्टूडियो", es:"Estudio", ar:"استوديو", fr:"Studio", bn:"স্টুডিও", pt:"Estúdio", ru:"Студия", ur:"اسٹوڈیو", id:"Studio", de:"Studio", ja:"スタジオ", tr:"Stüdyo", ko:"스튜디오", fa:"استودیو", uk:"Студія", it:"Studio", pl:"Studio", vi:"Studio" },
  trends: { en:"Trend Spotter", zh:"趋势雷达", hi:"ट्रेंड स्पॉटर", es:"Detector de Tendencias", ar:"راصد الاتجاهات", fr:"Détecteur de Tendances", bn:"ট্রেন্ড স্পটার", pt:"Radar de Tendências", ru:"Радар трендов", ur:"ٹرینڈ اسپاٹر", id:"Pemantau Tren", de:"Trend-Radar", ja:"トレンド探知", tr:"Trend Radarı", ko:"트렌드 탐지기", fa:"ردیاب ترند", uk:"Радар трендів", it:"Rileva Tendenze", pl:"Radar Trendów", vi:"Dò Xu Hướng" },
  ai: { en:"NovaClip AI", zh:"NovaClip 智能", hi:"NovaClip एआई", es:"IA NovaClip", ar:"ذكاء NovaClip", fr:"IA NovaClip", bn:"NovaClip এআই", pt:"IA NovaClip", ru:"ИИ NovaClip", ur:"NovaClip اے آئی", id:"AI NovaClip", de:"NovaClip KI", ja:"NovaClip AI", tr:"NovaClip YZ", ko:"NovaClip AI", fa:"هوش مصنوعی NovaClip", uk:"ШІ NovaClip", it:"IA NovaClip", pl:"AI NovaClip", vi:"AI NovaClip" },
  editor: { en:"Editor", zh:"编辑器", hi:"एडिटर", es:"Editor", ar:"المحرر", fr:"Éditeur", bn:"এডিটর", pt:"Editor", ru:"Редактор", ur:"ایڈیٹر", id:"Editor", de:"Editor", ja:"エディター", tr:"Editör", ko:"에디터", fa:"ویرایشگر", uk:"Редактор", it:"Editor", pl:"Edytor", vi:"Trình chỉnh sửa" },
  sniper: { en:"Sniper", zh:"狙击手", hi:"स्नाइपर", es:"Francotirador", ar:"قناص", fr:"Sniper", bn:"স্নাইপার", pt:"Sniper", ru:"Снайпер", ur:"سنائپر", id:"Sniper", de:"Sniper", ja:"スナイパー", tr:"Keskin Nişancı", ko:"스나이퍼", fa:"تک‌تیرانداز", uk:"Снайпер", it:"Cecchino", pl:"Snajper", vi:"Bắn tỉa" },
  background: { en:"Background", zh:"背景", hi:"बैकग्राउंड", es:"Fondo", ar:"الخلفية", fr:"Arrière-plan", bn:"ব্যাকগ্রাউন্ড", pt:"Fundo", ru:"Фон", ur:"پس منظر", id:"Latar", de:"Hintergrund", ja:"背景", tr:"Arka Plan", ko:"배경", fa:"پس‌زمینه", uk:"Тло", it:"Sfondo", pl:"Tło", vi:"Nền" },
  language: { en:"Language", zh:"语言", hi:"भाषा", es:"Idioma", ar:"اللغة", fr:"Langue", bn:"ভাষা", pt:"Idioma", ru:"Язык", ur:"زبان", id:"Bahasa", de:"Sprache", ja:"言語", tr:"Dil", ko:"언어", fa:"زبان", uk:"Мова", it:"Lingua", pl:"Język", vi:"Ngôn ngữ" },
  welcome: { en:"👋 Welcome to NovaClip!", zh:"👋 欢迎来到 NovaClip！", hi:"👋 NovaClip में आपका स्वागत है!", es:"👋 ¡Bienvenido a NovaClip!", ar:"👋 مرحبًا بك في NovaClip!", fr:"👋 Bienvenue sur NovaClip !", bn:"👋 NovaClip-এ স্বাগতম!", pt:"👋 Bem-vindo ao NovaClip!", ru:"👋 Добро пожаловать в NovaClip!", ur:"👋 NovaClip میں خوش آمدید!", id:"👋 Selamat datang di NovaClip!", de:"👋 Willkommen bei NovaClip!", ja:"👋 NovaClipへようこそ！", tr:"👋 NovaClip'e hoş geldin!", ko:"👋 NovaClip에 오신 것을 환영합니다!", fa:"👋 به NovaClip خوش آمدید!", uk:"👋 Ласкаво просимо до NovaClip!", it:"👋 Benvenuto su NovaClip!", pl:"👋 Witamy w NovaClip!", vi:"👋 Chào mừng đến với NovaClip!" },
  card_ai: { en:"NovaClip AI", zh:"NovaClip 智能", hi:"NovaClip एआई", es:"IA NovaClip", ar:"ذكاء NovaClip", fr:"IA NovaClip", bn:"NovaClip এআই", pt:"IA NovaClip", ru:"ИИ NovaClip", ur:"NovaClip اے آئی", id:"AI NovaClip", de:"NovaClip KI", ja:"NovaClip AI", tr:"NovaClip YZ", ko:"NovaClip AI", fa:"هوش مصنوعی NovaClip", uk:"ШІ NovaClip", it:"IA NovaClip", pl:"AI NovaClip", vi:"AI NovaClip" },
  card_ai_d: { en:"Three tutors — YouTube, Space and Business — answer in your language, tuned for teen creators.", zh:"三位导师——YouTube、太空和商业——用你的语言回答，为青少年创作者定制。", hi:"तीन ट्यूटर — YouTube, स्पेस और बिज़नेस — आपकी भाषा में जवाब देते हैं।", es:"Tres tutores — YouTube, Espacio y Negocios — responden en tu idioma, hechos para creadores jóvenes.", ar:"ثلاثة معلمين — يوتيوب والفضاء والأعمال — يجيبون بلغتك، مصمّمون للمبدعين الشباب.", fr:"Trois tuteurs — YouTube, Espace et Business — répondent dans ta langue, pensés pour les jeunes créateurs.", bn:"তিনজন টিউটর — YouTube, স্পেস ও বিজনেস — আপনার ভাষায় উত্তর দেয়।", pt:"Três tutores — YouTube, Espaço e Negócios — respondem na tua língua, feitos para jovens criadores.", ru:"Три наставника — YouTube, космос и бизнес — отвечают на твоём языке.", ur:"تین ٹیوٹر — یوٹیوب، خلا اور کاروبار — آپ کی زبان میں جواب دیتے ہیں۔", id:"Tiga tutor — YouTube, Luar Angkasa, dan Bisnis — menjawab dalam bahasamu.", de:"Drei Tutoren — YouTube, Weltraum und Business — antworten in deiner Sprache, gemacht für junge Creator.", ja:"3人のチューター — YouTube・宇宙・ビジネス — があなたの言語で答えます。", tr:"Üç eğitmen — YouTube, Uzay ve İş — senin dilinde cevap verir.", ko:"세 명의 튜터 — YouTube, 우주, 비즈니스 — 가 당신의 언어로 답합니다.", fa:"سه مربی — یوتیوب، فضا و کسب‌وکار — به زبان شما پاسخ می‌دهند.", uk:"Три наставники — YouTube, космос і бізнес — відповідають твоєю мовою.", it:"Tre tutor — YouTube, Spazio e Business — rispondono nella tua lingua.", pl:"Trzech tutorów — YouTube, Kosmos i Biznes — odpowiada w Twoim języku.", vi:"Ba gia sư — YouTube, Vũ trụ và Kinh doanh — trả lời bằng ngôn ngữ của bạn." },
  card_duel: { en:"Channel Duels", zh:"频道对决", hi:"चैनल ड्यूल", es:"Duelos de Canales", ar:"مبارزات القنوات", fr:"Duels de Chaînes", bn:"চ্যানেল ডুয়েল", pt:"Duelos de Canais", ru:"Дуэли каналов", ur:"چینل ڈوئل", id:"Duel Kanal", de:"Kanal-Duelle", ja:"チャンネル対決", tr:"Kanal Düelloları", ko:"채널 대결", fa:"دوئل کانال‌ها", uk:"Дуелі каналів", it:"Duelli tra Canali", pl:"Pojedynki Kanałów", vi:"Đấu Kênh" },
  card_duel_d: { en:"Battle channels within 20k subs of you. Subs and views decide the winner — win and bank points.", zh:"挑战与你相差2万订阅以内的频道。订阅和播放量决定胜负——获胜赚积分。", hi:"अपने से 20k सब्स के अंदर के चैनलों से लड़ें। जीतें और पॉइंट कमाएँ।", es:"Lucha contra canales a menos de 20k subs de ti. Gana y suma puntos.", ar:"نافس قنوات ضمن 20 ألف مشترك منك. اربح واجمع النقاط.", fr:"Affronte des chaînes à moins de 20k abonnés de toi. Gagne et empoche des points.", bn:"আপনার থেকে ২০ হাজার সাবের মধ্যে চ্যানেলের সাথে লড়ুন। জিতুন, পয়েন্ট নিন।", pt:"Batalha canais até 20k subs de diferença. Ganha e acumula pontos.", ru:"Сражайся с каналами в пределах 20 тыс. подписчиков. Побеждай и получай очки.", ur:"اپنے سے 20 ہزار سبس کے اندر چینلز سے مقابلہ کریں۔ جیتیں اور پوائنٹس کمائیں۔", id:"Lawan kanal dalam selisih 20k subs. Menang dan kumpulkan poin.", de:"Kämpfe gegen Kanäle mit max. 20k Abo-Abstand. Gewinne und sammle Punkte.", ja:"登録者差2万以内のチャンネルと対決。勝ってポイント獲得。", tr:"Senden en fazla 20k abone farkı olan kanallarla savaş. Kazan, puan topla.", ko:"당신과 2만 구독자 이내의 채널과 대결하세요. 이기고 포인트를 받으세요.", fa:"با کانال‌های تا ۲۰ هزار مشترک اختلاف مبارزه کن. ببر و امتیاز بگیر.", uk:"Бийся з каналами в межах 20 тис. підписників. Перемагай і збирай бали.", it:"Sfida canali entro 20k iscritti da te. Vinci e accumula punti.", pl:"Walcz z kanałami w granicach 20 tys. subów. Wygrywaj i zbieraj punkty.", vi:"Đấu với các kênh chênh lệch dưới 20k sub. Thắng và nhận điểm." },
  card_ana: { en:"Analytics", zh:"数据分析", hi:"एनालिटिक्स", es:"Analíticas", ar:"التحليلات", fr:"Analytique", bn:"অ্যানালিটিক্স", pt:"Análises", ru:"Аналитика", ur:"تجزیات", id:"Analitik", de:"Analysen", ja:"分析", tr:"Analizler", ko:"분석", fa:"تحلیل‌ها", uk:"Аналітика", it:"Analisi", pl:"Analityka", vi:"Phân tích" },
  card_ana_d: { en:"Your stats, best videos, and closest rivals — at a glance.", zh:"你的数据、最佳视频和最接近的对手，一目了然。", hi:"आपके आँकड़े, बेस्ट वीडियो और करीबी राइवल — एक नज़र में।", es:"Tus estadísticas, mejores vídeos y rivales más cercanos — de un vistazo.", ar:"إحصاءاتك وأفضل فيديوهاتك وأقرب منافسيك — بنظرة واحدة.", fr:"Tes stats, tes meilleures vidéos et tes rivaux les plus proches — en un clin d’œil.", bn:"আপনার পরিসংখ্যান, সেরা ভিডিও ও নিকটতম প্রতিদ্বন্দ্বী — এক নজরে।", pt:"As tuas estatísticas, melhores vídeos e rivais mais próximos — num relance.", ru:"Твоя статистика, лучшие видео и ближайшие соперники — с первого взгляда.", ur:"آپ کے اعداد و شمار، بہترین ویڈیوز اور قریبی حریف — ایک نظر میں۔", id:"Statistikmu, video terbaik, dan rival terdekat — sekilas.", de:"Deine Statistiken, besten Videos und nächsten Rivalen — auf einen Blick.", ja:"あなたの統計、ベスト動画、最接近のライバルを一目で。", tr:"İstatistiklerin, en iyi videoların ve en yakın rakiplerin — bir bakışta.", ko:"내 통계, 최고의 영상, 가장 가까운 라이벌 — 한눈에.", fa:"آمار تو، بهترین ویدیوها و نزدیک‌ترین رقبا — در یک نگاه.", uk:"Твоя статистика, найкращі відео та найближчі суперники — з першого погляду.", it:"Le tue statistiche, i migliori video e i rivali più vicini — a colpo d’occhio.", pl:"Twoje statystyki, najlepsze filmy i najbliżsi rywale — w mgnieniu oka.", vi:"Số liệu, video hay nhất và đối thủ gần nhất — trong nháy mắt." },
  card_quest: { en:"Rewards and Achievements", zh:"奖励与成就", hi:"रिवॉर्ड और अचीवमेंट", es:"Recompensas y Logros", ar:"الجوائز والإنجازات", fr:"Récompenses et Succès", bn:"পুরস্কার ও অর্জন", pt:"Recompensas e Conquistas", ru:"Награды и достижения", ur:"انعامات اور کامیابیاں", id:"Hadiah dan Pencapaian", de:"Belohnungen und Erfolge", ja:"リワードと実績", tr:"Ödüller ve Başarılar", ko:"보상과 업적", fa:"جوایز و دستاوردها", uk:"Нагороди та досягнення", it:"Ricompense e Obiettivi", pl:"Nagrody i Osiągnięcia", vi:"Phần thưởng và Thành tựu" },
  card_quest_d: { en:"Every action earns points. Hit the milestones, unlock free NovaClip Pro time.", zh:"每个操作都能赚积分。达到里程碑，解锁免费 NovaClip Pro。", hi:"हर एक्शन से पॉइंट मिलते हैं। माइलस्टोन पूरे करें, फ्री Pro पाएं।", es:"Cada acción suma puntos. Alcanza las metas y desbloquea NovaClip Pro gratis.", ar:"كل إجراء يكسبك نقاطًا. حقق الأهداف وافتح NovaClip Pro مجانًا.", fr:"Chaque action rapporte des points. Atteins les paliers, débloque du Pro gratuit.", bn:"প্রতিটি কাজে পয়েন্ট। মাইলস্টোন ছুঁয়ে ফ্রি Pro আনলক করুন।", pt:"Cada ação dá pontos. Atinge as metas e desbloqueia NovaClip Pro grátis.", ru:"Каждое действие даёт очки. Достигай целей — открывай бесплатный Pro.", ur:"ہر عمل پوائنٹس دیتا ہے۔ سنگ میل عبور کریں، مفت Pro کھولیں۔", id:"Setiap aksi menghasilkan poin. Capai target, buka Pro gratis.", de:"Jede Aktion bringt Punkte. Erreiche die Meilensteine, schalte gratis Pro frei.", ja:"行動すればポイント。マイルストーン達成で無料Proを解放。", tr:"Her eylem puan kazandırır. Hedeflere ulaş, ücretsiz Pro aç.", ko:"모든 행동이 포인트가 됩니다. 목표를 달성하고 무료 Pro를 열어보세요.", fa:"هر اقدامی امتیاز می‌دهد. به نقاط عطف برس و Pro رایگان باز کن.", uk:"Кожна дія дає бали. Досягай цілей — відкривай безплатний Pro.", it:"Ogni azione dà punti. Raggiungi i traguardi, sblocca Pro gratis.", pl:"Każda akcja daje punkty. Osiągaj cele, odblokuj darmowe Pro.", vi:"Mỗi hành động đều có điểm. Đạt mốc, mở khóa Pro miễn phí." },
  footer: { en:"Classic app with quizzes and streaks", zh:"带测验和连胜的经典应用", hi:"क्विज़ और स्ट्रीक वाला क्लासिक ऐप", es:"App clásica con quizzes y rachas", ar:"التطبيق الكلاسيكي مع الاختبارات", fr:"App classique avec quiz et séries", bn:"কুইজ ও স্ট্রিক সহ ক্লাসিক অ্যাপ", pt:"App clássica com quizzes e sequências", ru:"Классическое приложение с квизами", ur:"کوئز اور سٹریکس والی کلاسک ایپ", id:"Aplikasi klasik dengan kuis", de:"Klassische App mit Quiz und Serien", ja:"クイズと連続記録のクラシック版", tr:"Quiz ve serilerle klasik uygulama", ko:"퀴즈와 스트릭이 있는 클래식 앱", fa:"اپ کلاسیک با آزمون‌ها", uk:"Класичний застосунок із квізами", it:"App classica con quiz e serie", pl:"Klasyczna apka z quizami", vi:"Ứng dụng cổ điển với quiz" },
  signin: { en:"🔑 Sign in with Google", zh:"🔑 使用 Google 登录", hi:"🔑 Google से साइन इन करें", es:"🔑 Iniciar sesión con Google", ar:"🔑 تسجيل الدخول بجوجل", fr:"🔑 Se connecter avec Google", bn:"🔑 Google দিয়ে সাইন ইন", pt:"🔑 Entrar com Google", ru:"🔑 Войти через Google", ur:"🔑 گوگل سے سائن ان کریں", id:"🔑 Masuk dengan Google", de:"🔑 Mit Google anmelden", ja:"🔑 Googleでログイン", tr:"🔑 Google ile giriş yap", ko:"🔑 Google로 로그인", fa:"🔑 ورود با گوگل", uk:"🔑 Увійти через Google", it:"🔑 Accedi con Google", pl:"🔑 Zaloguj przez Google", vi:"🔑 Đăng nhập bằng Google" },
  signout: { en:"Sign out", zh:"退出登录", hi:"साइन आउट", es:"Cerrar sesión", ar:"تسجيل الخروج", fr:"Se déconnecter", bn:"সাইন আউট", pt:"Terminar sessão", ru:"Выйти", ur:"سائن آؤٹ", id:"Keluar", de:"Abmelden", ja:"ログアウト", tr:"Çıkış yap", ko:"로그아웃", fa:"خروج", uk:"Вийти", it:"Esci", pl:"Wyloguj", vi:"Đăng xuất" },
  t_stats: { en:"📈 My analytics", zh:"📈 我的数据", hi:"📈 मेरी एनालिटिक्स", es:"📈 Mis analíticas", ar:"📈 تحليلاتي", fr:"📈 Mes analytiques", bn:"📈 আমার অ্যানালিটিক্স", pt:"📈 As minhas análises", ru:"📈 Моя аналитика", ur:"📈 میرے تجزیات", id:"📈 Analitik saya", de:"📈 Meine Analysen", ja:"📈 マイ分析", tr:"📈 Analizlerim", ko:"📈 내 분석", fa:"📈 تحلیل‌های من", uk:"📈 Моя аналітика", it:"📈 Le mie analisi", pl:"📈 Moja analityka", vi:"📈 Phân tích của tôi" },
  t_comp: { en:"🥊 Closest competitors", zh:"🥊 最接近的对手", hi:"🥊 करीबी प्रतिद्वंद्वी", es:"🥊 Competidores cercanos", ar:"🥊 أقرب المنافسين", fr:"🥊 Concurrents proches", bn:"🥊 নিকটতম প্রতিযোগী", pt:"🥊 Concorrentes próximos", ru:"🥊 Ближайшие соперники", ur:"🥊 قریبی حریف", id:"🥊 Pesaing terdekat", de:"🥊 Nächste Konkurrenten", ja:"🥊 最接近のライバル", tr:"🥊 En yakın rakipler", ko:"🥊 가장 가까운 경쟁자", fa:"🥊 نزدیک‌ترین رقبا", uk:"🥊 Найближчі суперники", it:"🥊 Concorrenti più vicini", pl:"🥊 Najbliżsi rywale", vi:"🥊 Đối thủ gần nhất" },
  t_duel: { en:"⚔️ Duel a channel", zh:"⚔️ 频道对决", hi:"⚔️ चैनल से ड्यूल", es:"⚔️ Duelo con un canal", ar:"⚔️ نازل قناة", fr:"⚔️ Défier une chaîne", bn:"⚔️ চ্যানেল ডুয়েল", pt:"⚔️ Desafiar um canal", ru:"⚔️ Дуэль с каналом", ur:"⚔️ چینل سے ڈوئل", id:"⚔️ Duel dengan kanal", de:"⚔️ Kanal herausfordern", ja:"⚔️ チャンネル対決", tr:"⚔️ Bir kanalla düello", ko:"⚔️ 채널과 대결", fa:"⚔️ دوئل با یک کانال", uk:"⚔️ Дуель із каналом", it:"⚔️ Sfida un canale", pl:"⚔️ Pojedynek z kanałem", vi:"⚔️ Đấu với một kênh" },
  t_trend: { en:"🔥 Trending topics", zh:"🔥 热门话题", hi:"🔥 ट्रेंडिंग टॉपिक्स", es:"🔥 Temas en tendencia", ar:"🔥 المواضيع الرائجة", fr:"🔥 Sujets tendance", bn:"🔥 ট্রেন্ডিং টপিক", pt:"🔥 Tópicos em tendência", ru:"🔥 В тренде", ur:"🔥 ٹرینڈنگ موضوعات", id:"🔥 Topik tren", de:"🔥 Trend-Themen", ja:"🔥 トレンドの話題", tr:"🔥 Trend konular", ko:"🔥 인기 주제", fa:"🔥 موضوعات پرطرفدار", uk:"🔥 У тренді", it:"🔥 Argomenti di tendenza", pl:"🔥 Popularne tematy", vi:"🔥 Chủ đề thịnh hành" },
  studio_h: { en:"NovaClip Studio", zh:"NovaClip 工作室", hi:"NovaClip स्टूडियो", es:"Estudio NovaClip", ar:"استوديو NovaClip", fr:"Studio NovaClip", bn:"NovaClip স্টুডিও", pt:"Estúdio NovaClip", ru:"Студия NovaClip", ur:"NovaClip اسٹوڈیو", id:"Studio NovaClip", de:"NovaClip Studio", ja:"NovaClipスタジオ", tr:"NovaClip Stüdyo", ko:"NovaClip 스튜디오", fa:"استودیو NovaClip", uk:"Студія NovaClip", it:"Studio NovaClip", pl:"Studio NovaClip", vi:"Studio NovaClip" },
  compare: { en:"Compare with 2 competitors", zh:"与2个对手对比", hi:"2 प्रतिद्वंद्वियों से तुलना", es:"Comparar con 2 competidores", ar:"قارن مع منافسين اثنين", fr:"Comparer avec 2 concurrents", bn:"২ প্রতিযোগীর সাথে তুলনা", pt:"Comparar com 2 concorrentes", ru:"Сравнить с 2 соперниками", ur:"2 حریفوں سے موازنہ", id:"Bandingkan dengan 2 pesaing", de:"Mit 2 Konkurrenten vergleichen", ja:"ライバル2人と比較", tr:"2 rakiple karşılaştır", ko:"경쟁자 2명과 비교", fa:"مقایسه با ۲ رقیب", uk:"Порівняти з 2 суперниками", it:"Confronta con 2 concorrenti", pl:"Porównaj z 2 rywalami", vi:"So sánh với 2 đối thủ" },
  duel_label: { en:"⚔️ Views and subs duel (max 20k subs difference)", zh:"⚔️ 播放与订阅对决（最多相差2万订阅）", hi:"⚔️ व्यूज़ और सब्स ड्यूल (अधिकतम 20k अंतर)", es:"⚔️ Duelo de vistas y subs (máx. 20k de diferencia)", ar:"⚔️ مبارزة المشاهدات والمشتركين (فرق 20 ألف كحد أقصى)", fr:"⚔️ Duel vues et abonnés (écart max 20k)", bn:"⚔️ ভিউ ও সাব ডুয়েল (সর্বোচ্চ ২০ হাজার পার্থক্য)", pt:"⚔️ Duelo de views e subs (máx. 20k de diferença)", ru:"⚔️ Дуэль просмотров и подписчиков (макс. 20 тыс. разницы)", ur:"⚔️ ویوز اور سبس ڈوئل (زیادہ سے زیادہ 20 ہزار فرق)", id:"⚔️ Duel views dan subs (selisih maks 20k)", de:"⚔️ Views- und Abo-Duell (max. 20k Unterschied)", ja:"⚔️ 再生数と登録者の対決（差2万まで）", tr:"⚔️ İzlenme ve abone düellosu (en fazla 20k fark)", ko:"⚔️ 조회수·구독자 대결 (최대 2만 차이)", fa:"⚔️ دوئل بازدید و مشترک (حداکثر ۲۰ هزار اختلاف)", uk:"⚔️ Дуель переглядів і підписників (макс. 20 тис.)", it:"⚔️ Duello di views e iscritti (max 20k di differenza)", pl:"⚔️ Pojedynek wyświetleń i subów (maks. 20 tys. różnicy)", vi:"⚔️ Đấu lượt xem và sub (chênh tối đa 20k)" },
  opp_ph: { en:"Opponent channel name...", zh:"对手频道名称...", hi:"विरोधी चैनल का नाम...", es:"Nombre del canal rival...", ar:"اسم قناة الخصم...", fr:"Nom de la chaîne adverse...", bn:"প্রতিপক্ষ চ্যানেলের নাম...", pt:"Nome do canal adversário...", ru:"Название канала соперника...", ur:"مخالف چینل کا نام...", id:"Nama kanal lawan...", de:"Name des Gegner-Kanals...", ja:"相手チャンネル名...", tr:"Rakip kanal adı...", ko:"상대 채널 이름...", fa:"نام کانال حریف...", uk:"Назва каналу суперника...", it:"Nome del canale avversario...", pl:"Nazwa kanału rywala...", vi:"Tên kênh đối thủ..." },
  fight: { en:"Fight!", zh:"开战！", hi:"लड़ो!", es:"¡Pelea!", ar:"قاتِل!", fr:"Combat !", bn:"লড়াই!", pt:"Lutar!", ru:"В бой!", ur:"لڑو!", id:"Lawan!", de:"Kämpfen!", ja:"対戦！", tr:"Savaş!", ko:"대결!", fa:"مبارزه!", uk:"У бій!", it:"Combatti!", pl:"Walcz!", vi:"Chiến!" },
  ai_h: { en:"✨ NovaClip AI", zh:"✨ NovaClip 智能", hi:"✨ NovaClip एआई", es:"✨ IA NovaClip", ar:"✨ ذكاء NovaClip", fr:"✨ IA NovaClip", bn:"✨ NovaClip এআই", pt:"✨ IA NovaClip", ru:"✨ ИИ NovaClip", ur:"✨ NovaClip اے آئی", id:"✨ AI NovaClip", de:"✨ NovaClip KI", ja:"✨ NovaClip AI", tr:"✨ NovaClip YZ", ko:"✨ NovaClip AI", fa:"✨ هوش مصنوعی NovaClip", uk:"✨ ШІ NovaClip", it:"✨ IA NovaClip", pl:"✨ AI NovaClip", vi:"✨ AI NovaClip" },
  quests: { en:"🎁 Rewards", zh:"🎁 奖励", hi:"🎁 रिवॉर्ड्स", es:"🎁 Recompensas", ar:"🎁 الجوائز", fr:"🎁 Récompenses", bn:"🎁 পুরস্কার", pt:"🎁 Recompensas", ru:"🎁 Награды", ur:"🎁 انعامات", id:"🎁 Hadiah", de:"🎁 Belohnungen", ja:"🎁 リワード", tr:"🎁 Ödüller", ko:"🎁 보상", fa:"🎁 جوایز", uk:"🎁 Нагороди", it:"🎁 Ricompense", pl:"🎁 Nagrody", vi:"🎁 Phần thưởng" },
  achievements: { en:"🏅 Achievements", zh:"🏅 成就", hi:"🏅 उपलब्धियाँ", es:"🏅 Logros", ar:"🏅 الإنجازات", fr:"🏅 Succès", bn:"🏅 অর্জন", pt:"🏅 Conquistas", ru:"🏅 Достижения", ur:"🏅 کامیابیاں", id:"🏅 Pencapaian", de:"🏅 Erfolge", ja:"🏅 実績", tr:"🏅 Başarılar", ko:"🏅 업적", fa:"🏅 دستاوردها", uk:"🏅 Досягнення", it:"🏅 Obiettivi", pl:"🏅 Osiągnięcia", vi:"🏅 Thành tựu" },
  history: { en:"📜 History", zh:"📜 历史", hi:"📜 इतिहास", es:"📜 Historial", ar:"📜 السجل", fr:"📜 Historique", bn:"📜 ইতিহাস", pt:"📜 Histórico", ru:"📜 История", ur:"📜 تاریخ", id:"📜 Riwayat", de:"📜 Verlauf", ja:"📜 履歴", tr:"📜 Geçmiş", ko:"📜 기록", fa:"📜 تاریخچه", uk:"📜 Історія", it:"📜 Cronologia", pl:"📜 Historia", vi:"📜 Lịch sử" },
  ask: { en:"💬 Ask", zh:"💬 提问", hi:"💬 पूछें", es:"💬 Preguntar", ar:"💬 اسأل", fr:"💬 Demander", bn:"💬 জিজ্ঞাসা", pt:"💬 Perguntar", ru:"💬 Спросить", ur:"💬 پوچھیں", id:"💬 Tanya", de:"💬 Fragen", ja:"💬 質問", tr:"💬 Sor", ko:"💬 질문", fa:"💬 بپرس", uk:"💬 Запитати", it:"💬 Chiedi", pl:"💬 Zapytaj", vi:"💬 Hỏi" },
  thumb: { en:"🎨 Thumbnail", zh:"🎨 缩略图", hi:"🎨 थंबनेल", es:"🎨 Miniatura", ar:"🎨 صورة مصغرة", fr:"🎨 Miniature", bn:"🎨 থাম্বনেইল", pt:"🎨 Thumbnail", ru:"🎨 Превью", ur:"🎨 تھمب نیل", id:"🎨 Thumbnail", de:"🎨 Thumbnail", ja:"🎨 サムネイル", tr:"🎨 Küçük resim", ko:"🎨 썸네일", fa:"🎨 تصویر بندانگشتی", uk:"🎨 Прев’ю", it:"🎨 Miniatura", pl:"🎨 Miniatura", vi:"🎨 Ảnh thu nhỏ" },
  video: { en:"🎬 Video maker", zh:"🎬 视频制作", hi:"🎬 वीडियो मेकर", es:"🎬 Creador de vídeo", ar:"🎬 صانع الفيديو", fr:"🎬 Créateur vidéo", bn:"🎬 ভিডিও মেকার", pt:"🎬 Criador de vídeo", ru:"🎬 Создатель видео", ur:"🎬 ویڈیو میکر", id:"🎬 Pembuat video", de:"🎬 Video-Macher", ja:"🎬 動画メーカー", tr:"🎬 Video yapıcı", ko:"🎬 영상 제작", fa:"🎬 ویدیوساز", uk:"🎬 Творець відео", it:"🎬 Crea video", pl:"🎬 Kreator wideo", vi:"🎬 Tạo video" },
  trend_h: { en:"🛰️ Trend Spotter", zh:"🛰️ 趋势雷达", hi:"🛰️ ट्रेंड स्पॉटर", es:"🛰️ Detector de Tendencias", ar:"🛰️ راصد الاتجاهات", fr:"🛰️ Détecteur de Tendances", bn:"🛰️ ট্রেন্ড স্পটার", pt:"🛰️ Radar de Tendências", ru:"🛰️ Радар трендов", ur:"🛰️ ٹرینڈ اسپاٹر", id:"🛰️ Pemantau Tren", de:"🛰️ Trend-Radar", ja:"🛰️ トレンド探知", tr:"🛰️ Trend Radarı", ko:"🛰️ 트렌드 탐지기", fa:"🛰️ ردیاب ترند", uk:"🛰️ Радар трендів", it:"🛰️ Rileva Tendenze", pl:"🛰️ Radar Trendów", vi:"🛰️ Dò Xu Hướng" },
  trend_p: { en:"Type your niche and drop the radar — NovaClip AI predicts what's about to blow up.", zh:"输入你的领域并启动雷达——NovaClip AI 预测即将爆火的内容。", hi:"अपना निच लिखें और रडार चलाएँ — AI बताएगा क्या वायरल होगा।", es:"Escribe tu nicho y lanza el radar — la IA predice lo que va a explotar.", ar:"اكتب مجالك وأطلق الرادار — الذكاء الاصطناعي يتنبأ بما سينفجر.", fr:"Tape ta niche et lance le radar — l’IA prédit ce qui va exploser.", bn:"আপনার নিশ লিখুন, রাডার চালান — AI বলবে কী ভাইরাল হবে।", pt:"Escreve o teu nicho e lança o radar — a IA prevê o que vai bombar.", ru:"Введи свою нишу и запусти радар — ИИ предскажет, что взлетит.", ur:"اپنا نیش لکھیں اور ریڈار چلائیں — AI بتائے گا کیا وائرل ہوگا۔", id:"Ketik niche-mu dan jalankan radar — AI memprediksi yang akan meledak.", de:"Gib deine Nische ein und starte das Radar — die KI sagt voraus, was explodiert.", ja:"ニッチを入力してレーダー起動 — AIが次のバズを予測。", tr:"Nişini yaz, radarı çalıştır — YZ neyin patlayacağını tahmin eder.", ko:"니치를 입력하고 레이더를 돌리세요 — AI가 뜰 콘텐츠를 예측합니다.", fa:"حوزه‌ات را بنویس و رادار را بینداز — هوش مصنوعی پیش‌بینی می‌کند چه چیزی می‌ترکد.", uk:"Введи свою нішу й запусти радар — ШІ передбачить, що вибухне.", it:"Scrivi la tua nicchia e lancia il radar — l’IA prevede cosa esploderà.", pl:"Wpisz swoją niszę i odpal radar — AI przewidzi, co wybuchnie.", vi:"Nhập lĩnh vực và thả radar — AI dự đoán điều sắp bùng nổ." },
  niche_ph: { en:"Your niche (e.g. Minecraft, cooking, football)", zh:"你的领域（如 Minecraft、烹饪、足球）", hi:"आपका निच (जैसे Minecraft, कुकिंग, फुटबॉल)", es:"Tu nicho (ej. Minecraft, cocina, fútbol)", ar:"مجالك (مثل ماينكرافت، الطبخ، كرة القدم)", fr:"Ta niche (ex : Minecraft, cuisine, football)", bn:"আপনার নিশ (যেমন Minecraft, রান্না, ফুটবল)", pt:"O teu nicho (ex: Minecraft, culinária, futebol)", ru:"Твоя ниша (напр. Minecraft, кулинария, футбол)", ur:"آپ کا نیش (مثلاً Minecraft، کھانا، فٹبال)", id:"Niche-mu (mis. Minecraft, memasak, sepak bola)", de:"Deine Nische (z.B. Minecraft, Kochen, Fußball)", ja:"あなたのニッチ（例：マイクラ、料理、サッカー）", tr:"Nişin (örn. Minecraft, yemek, futbol)", ko:"니치 (예: 마인크래프트, 요리, 축구)", fa:"حوزه شما (مثلاً ماینکرافت، آشپزی، فوتبال)", uk:"Твоя ніша (напр. Minecraft, кулінарія, футбол)", it:"La tua nicchia (es. Minecraft, cucina, calcio)", pl:"Twoja nisza (np. Minecraft, gotowanie, piłka)", vi:"Lĩnh vực của bạn (VD: Minecraft, nấu ăn, bóng đá)" },
  scan: { en:"🛰️ Scan for trends", zh:"🛰️ 扫描趋势", hi:"🛰️ ट्रेंड स्कैन करें", es:"🛰️ Buscar tendencias", ar:"🛰️ افحص الاتجاهات", fr:"🛰️ Scanner les tendances", bn:"🛰️ ট্রেন্ড স্ক্যান", pt:"🛰️ Procurar tendências", ru:"🛰️ Сканировать тренды", ur:"🛰️ ٹرینڈز اسکین کریں", id:"🛰️ Pindai tren", de:"🛰️ Nach Trends suchen", ja:"🛰️ トレンドをスキャン", tr:"🛰️ Trendleri tara", ko:"🛰️ 트렌드 스캔", fa:"🛰️ اسکن ترندها", uk:"🛰️ Сканувати тренди", it:"🛰️ Scansiona tendenze", pl:"🛰️ Skanuj trendy", vi:"🛰️ Quét xu hướng" },
  scanning: { en:"Scanning the airwaves...", zh:"正在扫描电波...", hi:"एयरवेव्स स्कैन हो रही हैं...", es:"Escaneando las ondas...", ar:"جارٍ مسح الموجات...", fr:"Analyse des ondes...", bn:"এয়ারওয়েভ স্ক্যান হচ্ছে...", pt:"A analisar o espetro...", ru:"Сканируем эфир...", ur:"ایئر ویوز اسکین ہو رہی ہیں...", id:"Memindai gelombang...", de:"Scanne die Wellen...", ja:"電波をスキャン中...", tr:"Dalgalar taranıyor...", ko:"전파를 스캔 중...", fa:"در حال اسکن امواج...", uk:"Скануємо ефір...", it:"Scansione delle onde...", pl:"Skanowanie fal...", vi:"Đang quét sóng..." },
  how1: { en:"Type your niche", zh:"输入你的领域", hi:"अपना निच लिखें", es:"Escribe tu nicho", ar:"اكتب مجالك", fr:"Tape ta niche", bn:"নিশ লিখুন", pt:"Escreve o teu nicho", ru:"Введи нишу", ur:"نیش لکھیں", id:"Ketik niche", de:"Nische eingeben", ja:"ニッチを入力", tr:"Nişini yaz", ko:"니치 입력", fa:"حوزه را بنویس", uk:"Введи нішу", it:"Scrivi la nicchia", pl:"Wpisz niszę", vi:"Nhập lĩnh vực" },
  how2: { en:"The radar sweeps the trends", zh:"雷达扫描趋势", hi:"रडार ट्रेंड्स खोजता है", es:"El radar barre las tendencias", ar:"الرادار يمسح الاتجاهات", fr:"Le radar balaie les tendances", bn:"রাডার ট্রেন্ড খোঁজে", pt:"O radar varre as tendências", ru:"Радар ищет тренды", ur:"ریڈار ٹرینڈز ڈھونڈتا ہے", id:"Radar memindai tren", de:"Das Radar scannt Trends", ja:"レーダーがトレンドを探索", tr:"Radar trendleri tarar", ko:"레이더가 트렌드를 훑습니다", fa:"رادار ترندها را می‌کاود", uk:"Радар шукає тренди", it:"Il radar scandaglia i trend", pl:"Radar skanuje trendy", vi:"Radar quét xu hướng" },
  how3: { en:"Get 6 rising video ideas", zh:"获得6个上升期视频灵感", hi:"6 उभरते वीडियो आइडिया पाएं", es:"Recibe 6 ideas en ascenso", ar:"احصل على 6 أفكار صاعدة", fr:"Reçois 6 idées montantes", bn:"৬টি উদীয়মান আইডিয়া পান", pt:"Recebe 6 ideias em ascensão", ru:"Получи 6 растущих идей", ur:"6 ابھرتے آئیڈیاز پائیں", id:"Dapatkan 6 ide naik daun", de:"Erhalte 6 aufsteigende Ideen", ja:"急上昇アイデアを6つ入手", tr:"Yükselen 6 fikir al", ko:"뜨는 아이디어 6개 받기", fa:"۶ ایده در حال رشد بگیر", uk:"Отримай 6 ідей, що зростають", it:"Ottieni 6 idee in crescita", pl:"Zdobądź 6 rosnących pomysłów", vi:"Nhận 6 ý tưởng đang lên" },
  recent: { en:"Recent scans", zh:"最近扫描", hi:"हाल के स्कैन", es:"Escaneos recientes", ar:"عمليات المسح الأخيرة", fr:"Scans récents", bn:"সাম্প্রতিক স্ক্যান", pt:"Análises recentes", ru:"Недавние сканы", ur:"حالیہ اسکینز", id:"Pindaian terbaru", de:"Letzte Scans", ja:"最近のスキャン", tr:"Son taramalar", ko:"최근 스캔", fa:"اسکن‌های اخیر", uk:"Останні сканування", it:"Scansioni recenti", pl:"Ostatnie skany", vi:"Lần quét gần đây" },
};

function lang() { return localStorage.getItem('nc_lang') || 'en'; }
function tr(key) { return (T[key] && T[key][lang()]) || (T[key] && T[key].en) || ''; }
function langInstruction() { return ' Reply ONLY in this language: ' + (LANGS[lang()] || 'English') + '. '; }
function applyLang(code) {
  localStorage.setItem('nc_lang', code);
  document.documentElement.lang = code;
  document.documentElement.dir = RTL.includes(code) ? 'rtl' : 'ltr';
  document.querySelectorAll('[data-t]').forEach(el => { const v = tr(el.dataset.t); if (v) el.textContent = v; });
  document.querySelectorAll('[data-tph]').forEach(el => { const v = tr(el.dataset.tph); if (v) el.placeholder = v; });
}

const QUESTS = [[100,'🎁 1 day free NovaClip Pro'],[450,'🎁 1 week free NovaClip Pro'],[700,'🎁 2 weeks free NovaClip Pro'],[1250,'🎁 1 month free NovaClip Pro']];
const ACHIEVEMENTS = [[30,'🏅 Reached 30 points'],[100,'🏅 Reached 100 points'],[250,'🏅 Reached 250 points'],[500,'🏅 Reached 500 points']];

const style = document.createElement('style');
style.textContent =
/* dropdown fix: dark options everywhere (fixes white-on-white lists) */
"select { background:#0A0C14 !important; color:#EAF2FF !important; border:1px solid rgba(0,240,255,0.35) !important; }" +
"select option { background:#0A0C14; color:#EAF2FF; }" +
/* futuristic sidebar upgrade — applies on every page over local styles */
".sidebar { background: linear-gradient(180deg, rgba(8,9,16,0.96), rgba(10,8,20,0.96)) !important; border-right:1px solid rgba(0,240,255,0.18) !important; box-shadow: 8px 0 40px rgba(0,240,255,0.05); }" +
".sidebar::before { content:''; position:absolute; top:0; right:-1px; bottom:0; width:2px; background:linear-gradient(180deg, transparent, #00F0FF, #FF2E97, transparent); opacity:0.5; animation: ncRail 5s ease-in-out infinite; }" +
"@keyframes ncRail { 0%,100% { opacity:0.35; } 50% { opacity:0.9; } }" +
".sidebar a { position:relative; letter-spacing:0.3px; transition: all 0.25s !important; }" +
".sidebar a::after { content:''; position:absolute; left:14px; right:14px; bottom:6px; height:1px; background:linear-gradient(90deg,#00F0FF,transparent); transform:scaleX(0); transform-origin:left; transition:transform 0.3s; }" +
".sidebar a:hover { background: rgba(0,240,255,0.08) !important; text-shadow:0 0 12px rgba(0,240,255,0.6); padding-left:26px !important; }" +
".sidebar a:hover::after { transform:scaleX(1); }" +
".sidebar a.aidot { background: linear-gradient(135deg,#FF2E97,#7209B7,#00F0FF) !important; background-size:220% 220% !important; animation: ncGrad 4s ease infinite; box-shadow:0 0 24px rgba(255,46,151,0.35); }" +
"@keyframes ncGrad { 0%,100% { background-position:0% 50%; } 50% { background-position:100% 50%; } }" +
"#nctoast { position:fixed; top:20px; right:20px; background:linear-gradient(90deg,#FF2E97,#7209B7); color:white; padding:14px 22px; border-radius:14px; font-weight:700; box-shadow:0 4px 20px rgba(0,0,0,0.5); z-index:9999; display:none; }" +
"#ncpts { position:fixed; top:16px; right:16px; background:rgba(10,12,20,0.9); color:#EAF2FF; border:1px solid rgba(0,240,255,0.4); border-radius:20px; padding:6px 14px; font-weight:700; z-index:997; box-shadow:0 0 18px rgba(0,240,255,0.15); }" +
".radar { width:220px; height:220px; border-radius:50%; margin:30px auto; position:relative; background:radial-gradient(circle,rgba(76,201,240,0.12) 0%,rgba(14,17,23,0.6) 70%); border:2px solid rgba(76,201,240,0.5); box-shadow:0 0 30px rgba(76,201,240,0.3) inset; overflow:hidden; }" +
".radar::before,.radar::after { content:''; position:absolute; inset:0; border-radius:50%; border:1px solid rgba(76,201,240,0.25); margin:40px; }" +
".radar::after { margin:80px; }" +
".radar .sweep { position:absolute; inset:0; border-radius:50%; background:conic-gradient(from 0deg,rgba(76,201,240,0.55) 0deg,rgba(76,201,240,0) 60deg,transparent 360deg); animation:ncsweep 1.6s linear infinite; }" +
"@keyframes ncsweep { to { transform:rotate(360deg); } }";
document.head.appendChild(style);

function applyTheme(name) { const t = THEMES[name] || THEMES['Dark']; document.documentElement.style.setProperty('--bg',t[0]); document.documentElement.style.setProperty('--box',t[1]); document.documentElement.style.setProperty('--txt',t[2]); document.body.dataset.theme = name; localStorage.setItem('nc_theme',name); }
function toast(msg) { const t = document.getElementById('nctoast'); if (!t) return; t.textContent = msg; t.style.display = 'block'; clearTimeout(t.hideTimer); t.hideTimer = setTimeout(() => { t.style.display = 'none'; }, 3000); }
function getPts() { return parseInt(localStorage.getItem('nc_points') || '0'); }
function checkUnlocks(pts) { const u = JSON.parse(localStorage.getItem('nc_unlocked') || '[]'); for (const [need,name] of QUESTS.concat(ACHIEVEMENTS)) { if (pts >= need && !u.includes(name)) { u.push(name); setTimeout(() => toast('🎉 UNLOCKED: ' + name), 1200); } } localStorage.setItem('nc_unlocked', JSON.stringify(u)); }
function addPts(n) { const p = getPts() + n; localStorage.setItem('nc_points', p); const b = document.getElementById('ncpts'); if (b) b.textContent = '🏆 ' + p + ' pts'; toast('+' + n + ' pts!'); checkUnlocks(p); refreshPanels(); }
function saveHist(subject,q,a) { const h = JSON.parse(localStorage.getItem('nc_history') || '{}'); if (!h[subject]) h[subject] = []; h[subject].push([q,a.slice(0,200)]); if (h[subject].length > 10) h[subject].shift(); localStorage.setItem('nc_history', JSON.stringify(h)); refreshPanels(); }
function refreshPanels() {
  const pts = getPts();
  const ql = document.getElementById('questlist'); if (ql) ql.innerHTML = QUESTS.map(([need,name]) => pts >= need ? name + ' — DONE ✅' : name + ' — ' + (need - pts) + ' pts to go 🔒').join('<br>');
  const al = document.getElementById('achlist'); if (al) al.innerHTML = ACHIEVEMENTS.map(([need,name]) => pts >= need ? name + ' ✅' : '🔒 Reach ' + need + ' points (you have ' + pts + ')').join('<br>');
  const hl = document.getElementById('histlist'); if (hl) { const h = JSON.parse(localStorage.getItem('nc_history') || '{}'); let html = ''; for (const s in h) { html += '<b>' + s + '</b> (' + h[s].length + ' chats)<br>' + h[s].slice(-3).map(x => '• ' + x[0]).join('<br>') + '<br><br>'; } hl.innerHTML = html || 'No chats yet - start talking!'; }
}
window.addEventListener('DOMContentLoaded', () => {
  const badge = document.createElement('div'); badge.id = 'ncpts'; badge.textContent = '🏆 ' + getPts() + ' pts'; document.body.appendChild(badge);
  const t = document.createElement('div'); t.id = 'nctoast'; document.body.appendChild(t);
  const pick = document.getElementById('themepick');
  if (pick) { for (const name in THEMES) { const o = document.createElement('option'); o.value = name; o.textContent = name; pick.appendChild(o); } pick.value = localStorage.getItem('nc_theme') || 'Dark'; pick.onchange = () => applyTheme(pick.value); }
  const lpick = document.getElementById('langpick');
  if (lpick) { for (const c in LANGS) { const o = document.createElement('option'); o.value = c; o.textContent = LANGS[c]; lpick.appendChild(o); } lpick.value = lang(); lpick.onchange = () => applyLang(lpick.value); }
  applyTheme(localStorage.getItem('nc_theme') || 'Dark');
  applyLang(lang());
  refreshPanels();

  // extra sidebar links (Family / Pricing) injected on every page
  const sb = document.querySelector('.sidebar .themewrap');
  if (sb && !document.getElementById('ncfamlink')) {
    const fam = document.createElement('a'); fam.id = 'ncfamlink'; fam.href = 'parent.html'; fam.textContent = '👨‍👩‍👧 Family';
    const pri = document.createElement('a'); pri.href = 'pricing.html'; pri.textContent = '💳 Pricing';
    sb.parentNode.insertBefore(fam, sb); sb.parentNode.insertBefore(pri, sb);
  }

  applySeason();
});

/* ===== SEASONAL EVENTS — automatic by date, no button =====
   Fixed dates use MM-DD every year; movable feasts (Islamic calendar, Easter,
   Diwali, Chinese New Year) use explicit dates per year (2026–2028). */
const SEASONS = [
  { name: 'Ramadan',        emo: '🌙✨🕌',  color: '#7bd4a8', ranges: [['2026-02-18','2026-03-19'],['2027-02-08','2027-03-09'],['2028-01-28','2028-02-26']], greet: 'Ramadan Kareem!' },
  { name: 'Eid al-Fitr',    emo: '🌙🎉🍬',  color: '#ffd166', ranges: [['2026-03-20','2026-03-23'],['2027-03-10','2027-03-13'],['2028-02-27','2028-03-01']], greet: 'Eid Mubarak!' },
  { name: 'Eid al-Adha',    emo: '🕌🐑💚',  color: '#8fd694', ranges: [['2026-05-26','2026-05-30'],['2027-05-16','2027-05-20'],['2028-05-04','2028-05-08']], greet: 'Eid Mubarak!' },
  { name: 'Halloween',      emo: '🎃👻🦇',  color: '#ff8c42', ranges: 'yearly:10-24:11-01', greet: 'Happy Halloween!' },
  { name: 'Christmas',      emo: '🎄❄️🎁',  color: '#ff5d5d', ranges: 'yearly:12-14:12-26', greet: 'Merry Christmas!' },
  { name: 'New Year',       emo: '🎆🥳✨',  color: '#ffd700', ranges: 'yearly:12-27:01-02', greet: 'Happy New Year!' },
  { name: 'Easter',         emo: '🐣🌸🥚',  color: '#c3a6ff', ranges: [['2026-03-30','2026-04-06'],['2027-03-22','2027-03-29'],['2028-04-10','2028-04-17']], greet: 'Happy Easter!' },
  { name: 'Diwali',         emo: '🪔✨🎇',  color: '#ffb347', ranges: [['2026-11-05','2026-11-10'],['2027-10-25','2027-10-30'],['2028-10-14','2028-10-19']], greet: 'Happy Diwali!' },
  { name: 'Chinese New Year', emo: '🧧🐉🏮', color: '#ff4d4d', ranges: [['2026-02-15','2026-02-19'],['2027-02-04','2027-02-08'],['2028-01-24','2028-01-28']], greet: 'Happy New Year!' }
];
function seasonActive(s, now) {
  const pad = n => (n < 10 ? '0' : '') + n;
  if (typeof s.ranges === 'string') {
    const [, a, b] = s.ranges.split(':');
    const md = pad(now.getMonth()+1) + '-' + pad(now.getDate());
    if (a <= b) return md >= a && md <= b;
    return md >= a || md <= b; // wraps year end (New Year)
  }
  const today = now.toISOString().slice(0,10);
  return s.ranges.some(([a,b]) => today >= a && today <= b);
}
function applySeason() {
  const now = new Date();
  const s = SEASONS.find(x => seasonActive(x, now));
  if (!s) return;
  const bar = document.createElement('div');
  bar.style.cssText = 'position:fixed;top:0;left:0;right:0;z-index:996;text-align:center;padding:6px 10px;font-weight:700;font-size:0.85rem;color:#0a0a12;background:' + s.color + ';box-shadow:0 2px 20px ' + s.color + '55;';
  bar.textContent = s.emo + '  ' + s.greet + '  ' + s.emo;
  document.body.appendChild(bar);
  document.body.style.paddingTop = '32px';
  // gentle falling emojis
  const emos = [...s.emo].filter(ch => ch.trim() && ch.codePointAt(0) > 255);
  for (let i = 0; i < 12; i++) {
    const e = document.createElement('div');
    e.textContent = emos[i % emos.length] || '✨';
    e.style.cssText = 'position:fixed;top:-30px;z-index:995;pointer-events:none;font-size:' + (14 + Math.random()*14) + 'px;left:' + (Math.random()*100) + 'vw;opacity:0.8;animation:ncfall ' + (7 + Math.random()*8) + 's linear ' + (Math.random()*10) + 's infinite;';
    document.body.appendChild(e);
  }
  const st = document.createElement('style');
  st.textContent = '@keyframes ncfall { from { transform: translateY(0) rotate(0deg); } to { transform: translateY(110vh) rotate(360deg); } }';
  document.head.appendChild(st);
}
