/* One mark, three colourways: the Nova explosion.
   ===========================================================================
   Asked for a star explosion, which is lucky, because that is what a nova is —
   the name has been describing the shape all along.

   Written as a generator rather than three hand-drawn files so the three sites
   cannot drift apart. The geometry is defined once; a brand supplies four
   colours and one optional cue inside the core. Change the shape here and all
   three change together.

   WHAT IT HAS TO SURVIVE

   A favicon is 16 pixels. Everything clever disappears at that size, so the
   mark is built in layers of decreasing importance: the four-point burst
   carries it alone, the shockwave ring and the debris are there at 64px and
   above, and the fine detail is allowed to vanish. That is why the burst is
   fat-bodied with concave flanks rather than a thin sparkle — a thin sparkle
   at 16px is a smudge.

   Flat colour, no filters: SVG filters are expensive to rasterise at large
   sizes and are dropped outright by some feed readers and email clients. The
   glow is a radial gradient, which is not.
   =========================================================================== */
import fs from 'node:fs';
import path from 'node:path';

const BRANDS = {
  novaclip: {
    file: '/home/user/novaclip-site/logo.svg',
    label: 'NovaClip',
    hot: '#EAFEFF',      // the core, near white
    core: '#2AD7D7',     // the burst body
    edge: '#00BCC5',     // the burst tips and ring
    halo: '#00BCC5',
    /* NovaClip keeps its play triangle, cut out of the core rather than laid
       on top, so the shape still says "video" in one flat colour. */
    cue: 'play'
  },
  novatools: {
    file: '/home/user/novaclip-site/novatools/logo.svg',
    label: 'NovaTools',
    hot: '#EAF0FF',
    core: '#4C7BF0',
    edge: '#2867E4',
    halo: '#2867E4',
    cue: null
  },
  novaclassics: {
    /* Vite copies src/public into the build, so the mark reaches the
       published site instead of sitting in the repo unused. */
    file: '/home/user/novaboomers/src/public/logo.svg',
    label: 'NovaClassics',
    /* Warm rather than electric: this one sits on cream paper beside a serif
       typeface, and a neon burst would look like it had wandered in from a
       different site. */
    hot: '#FDFCF9',
    core: '#7C8C77',
    edge: '#5D6B5D',
    halo: '#8A6A4B',
    cue: null
  }
};

/* ---- the geometry, once -------------------------------------------------- */

/* The four-point burst. Concave flanks (the quadratic control points pulled in
   towards the centre) are what make it read as light rather than as a plus
   sign. */
const BURST = 'M32 2 Q35.5 26 62 32 Q35.5 38 32 62 Q28.5 38 2 32 Q28.5 26 32 2 Z';

/* The same shape at 45°, half size: the diagonal flare of the explosion. */
const DIAGONALS = 'M32 12 Q33.8 27.5 52 32 Q33.8 36.5 32 52 Q30.2 36.5 12 32 Q30.2 27.5 32 12 Z';

/* Debris: eight fragments thrown outward, at the eight compass points, small
   enough to disappear cleanly at favicon size. */
function debris(colour) {
  const bits = [];
  for (let i = 0; i < 8; i++) {
    const a = (i * 45 + 22.5) * Math.PI / 180;
    const r = i % 2 === 0 ? 27 : 24.5;
    const x = 32 + Math.cos(a) * r;
    const y = 32 + Math.sin(a) * r;
    const size = i % 2 === 0 ? 1.9 : 1.3;
    bits.push(`<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${size}" fill="${colour}" opacity="${i % 2 === 0 ? 0.55 : 0.35}"/>`);
  }
  return bits.join('\n    ');
}

/* The favicon is a different drawing, not the same one scaled.
   At 16 pixels the shockwave ring and the debris are three grey pixels of
   noise sitting on top of the only part that carries the meaning. So the tab
   icon is the burst and the core alone, drawn slightly fatter to hold its
   colour when a browser resamples it. */
function favicon(b) {
  const id = b.label.toLowerCase() + '-f';
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="32" height="32" role="img" aria-label="${b.label}">
  <defs>
    <linearGradient id="${id}" x1="0.15" y1="0" x2="0.85" y2="1">
      <stop offset="0%" stop-color="${b.core}"/>
      <stop offset="100%" stop-color="${b.edge}"/>
    </linearGradient>
  </defs>
  <path d="${BURST}" fill="url(#${id})"/>
  <circle cx="32" cy="32" r="7" fill="${b.hot}"/>
</svg>
`;
}

function svg(b, size = 64) {
  const id = b.label.toLowerCase();
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="${size}" height="${size}" role="img" aria-label="${b.label}">
  <!-- The Nova mark: a star explosion. Generated by scratchpad/make-logos.mjs —
       edit that, not this, or the three sites drift apart. -->
  <defs>
    <radialGradient id="${id}-halo" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="${b.halo}" stop-opacity="0.45"/>
      <stop offset="55%" stop-color="${b.halo}" stop-opacity="0.13"/>
      <stop offset="100%" stop-color="${b.halo}" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="${id}-body" x1="0.15" y1="0" x2="0.85" y2="1">
      <stop offset="0%" stop-color="${b.core}"/>
      <stop offset="100%" stop-color="${b.edge}"/>
    </linearGradient>
    ${b.cue === 'play' ? `<mask id="${id}-cut">
      <rect width="64" height="64" fill="#fff"/>
      <path d="M28.5 26.5 L40 32 L28.5 37.5 Z" fill="#000"/>
    </mask>` : ''}
  </defs>

  <!-- the light it throws -->
  <circle cx="32" cy="32" r="31" fill="url(#${id}-halo)"/>

  <!-- the shockwave, still expanding -->
  <circle cx="32" cy="32" r="25.5" fill="none" stroke="${b.edge}" stroke-opacity="0.32"
          stroke-width="1.3" stroke-dasharray="7 5.5" stroke-linecap="round"/>

  <!-- what it threw off -->
  <g>
    ${debris(b.edge)}
  </g>

  <!-- the burst itself: the part that has to work alone at 16 pixels -->
  <g${b.cue === 'play' ? ` mask="url(#${id}-cut)"` : ''}>
    <path d="${DIAGONALS}" fill="${b.edge}" opacity="0.55" transform="rotate(45 32 32)"/>
    <path d="${BURST}" fill="url(#${id}-body)"/>
    <circle cx="32" cy="32" r="6.5" fill="${b.hot}"/>
  </g>
</svg>
`;
}

for (const [name, b] of Object.entries(BRANDS)) {
  fs.mkdirSync(path.dirname(b.file), { recursive: true });
  fs.writeFileSync(b.file, svg(b));
  console.log(`${b.label.padEnd(13)} -> ${b.file}`);
  const fav = path.join(path.dirname(b.file), 'favicon.svg');
  fs.writeFileSync(fav, favicon(b));
  console.log(`${''.padEnd(13)}    ${fav}`);
}
